### ISSUE TITLE
execute.cursor with parameters

### ISSUE THREAD

**Issue by Fredehagelund92** [blue-yonder/turbodbc#101]
After going through the documentation and api reference, it became clear i needed to use the parameter in the execute() function, however i keep getting following error:

```
turbodbc.exceptions.DatabaseError: ODBC error
state: 42000
native error code: -1
message: [EXASOL][EXASolution driver]syntax error, unexpected '?', expecting identifier_chain2 or OFFSET_ [line 1, column 19] 
```

code:

```
cursor.execute("create connection ? to ? user ? identified by ?", [obj['system_name'], obj['connection_string'], obj['username'], obj['password']])
```

From documentation:
```
cursor.execute("INSERT INTO TABLE my_integer_table VALUES (?, ?)", [42, 17])
```

**Comment by MathMagique** [comment]
You are reading the documentation correctly, you are supposed to use question marks to mark that you want to use a parameter. From the error message, however, it looks like using a parameter marker (at least in the first location) is not supported by your database in this kind of statement. From the Exasol manual (I assume that is the database you are using), it is not clear which things may be parameters and which are hard-coded things.

Playing around with my local Exasol instance, I found that _all_ parameters in your particular command need to be plain identifiers/strings. So what you could do is something like
```
cursor.execute("create connection {} to {} user {} identified by {}".format(obj['system_name'], obj['connection_string'], obj['username'], obj['password']))
```

**Comment by MathMagique** [comment]
There is not much that can be done on the turbodbc side, because it essentially passes the string on to unixodbc and the ODBC driver for parsing. Thus, I'll close this issue. You might consider asking your database vendor whether they could support parameters in such queries.
