### ISSUE TITLE
is windows 32bit support complex to add ? (for python-3.5+)

### ISSUE THREAD

**Issue by stonebig** [blue-yonder/turbodbc#103]

**Comment by MathMagique** [comment]
Hi! To be honest, I don't know. The last time I developed for a 32 bit system was 10 years ago, and it wasn't Windows to begin with. I would expect a few data types to be different in both Windows and ODBC headers, but I have no estimate as to how it would affect the turbodbc code base.

What is your use case that requires 32-bit Windows support?

**Comment by stonebig** [comment]
Users with 32bit Windows... not everybody has been able (or authorized) to transition to 64 bit yet.

Users stiucked on Office 32bit may also be better under a 32 bit Python.

**Comment by MathMagique** [comment]
Hi! I'll close this as won't fix right now, as I do not have time or resources to fix this any time soon. If someone wishes to contribute this including 32/64 bit builds on AppVeyor, I'll be happy to accept the contribution, though.
