### ISSUE TITLE
Import of datetime columns with nanosecond precision

### ISSUE THREAD

**Issue by bdanielby** [blue-yonder/turbodbc#112]
When importing dateframes into a database using `turbodbc`, I had problems with datetime columns 
with nanosecond precision and I found a fix:

Pandas uses nanosecond precision by default, e.g. if you use 
`df = pd.DataFrame({'A': pd.to_datetime(['2017-07-30', None])})`
In `turbodbc_numpy.insert_numpy`, this is not converted correctly in a dataframe import leading to 
error messages like

`message: [EXASOL][EXASolution driver]Feature not supported: Cannot cast from DECIMAL(20,0) to TIMESTAMP (Session: ...)`

I fixed this by adding a further if clause to `_convert_array` within `insert_numpy.py`:

```
    def _convert_array(array):
        dtype = getattr(array, 'dtype', None)
        if dtype == '<M8[us]':
            return array.astype(datetime.datetime)
        elif dtype == '<M8[ns]':
            return array.astype('<M8[us]').astype(datetime.datetime)
        else:
            return array
```

The double conversion -- first to microsecond precision, then to datetime.datetime -- is necessary
because the direct conversion to datetime.datetime doesn't work. (For details, see the discussion
on https://stackoverflow.com/questions/19502506/convert-numpy-datetime64-to-string-object-in-python?noredirect=1&lq=1  starting from "Interestingly, the numpy developers decided ...").

**Comment by bdanielby** [comment]
I tested this with an Exasol table with a TIMESTAMP column, e.g.:
```
CREATE or replace TABLE tutorial (A timestamp);
INSERT INTO tutorial VALUES ('2017-07-13');
INSERT INTO tutorial VALUES ('2017-07-18');
INSERT INTO tutorial VALUES (null);
select * from tutorial;
```

**Comment by MathMagique** [comment]
This issue references custom (private) wrapper code that is not part of turbodbc, but turbodbc's own code has a similar issue. I have captured this issue in #115. I am closing this one to avoid confusion due to the wrapper code snippets.
