### ISSUE TITLE
Connect to SQL Servre using turbodbc + FreeTDS from Conda on Linux

### ISSUE THREAD

**Issue by smontanaro** [blue-yonder/turbodbc#116]
Connecting to databases using ODBC has always mystified me. I'm trying to use turbodbc + FreeTDS in a Conda environment. I'm happy to connect without constructing a connection string, but I can't figure out what to give for the driver parameter. I think I'm supposed to provide a path to a shared object file it can dlopen(), but what exactly is that? Looking through the Conda meta files for the various packages I don't see anything which looks like it would be used to connect to SQL Server. I see lib/libsybdb.so in the freetds package (for Sybase, I presume), and lib/libodbc.so in the unixodbc package. What's the correct driver parameter? Once I've located a .so file, can it be specified using a relative path?

**Comment by MathMagique** [comment]
Hi there! I would be lying if I said I was never mystified by the stack myself, so you are not alone there ;-).

Have you checked the [turbodbc documentation on using MSSQL with FreeTDS](http://turbodbc.readthedocs.io/en/latest/pages/databases/mssql.html#microsoft-sql-server-mssql)? You are looking for a file named `libtdsodbc.so`. Probably it is not part of your conda environment, but your OS. Try looking at `/usr/local/lib/`.

A relative path could work, but I usually use an absolute one.

Also check out the documentation on [configuring ODBC](http://turbodbc.readthedocs.io/en/latest/pages/odbc/driver_manager_config.html), it mightprovide some useful information to understand ODBC a bit better.

**Comment by MathMagique** [comment]
@smontanaro Any luck with my suggestions?

**Comment by MathMagique** [comment]
Closed for the moment due to lack of feedback :-)
