### ISSUE TITLE
connection string creation

### ISSUE THREAD

**Issue by paolof89** [blue-yonder/turbodbc#117]
Hi, 
very interesting project!
I what to ask you if is there a function to create the connection string starting form some attributes.

For example in SqlAlchemy there area the URL and make_url functions (from sqlalchemy.engine.url import URL, make_url) to create the connection string in the proper way for sqlachemy library.

**Comment by MathMagique** [comment]
Hi! Turbodbc will automatically construct a connection string when you pass in keyword arguments ([see here](http://turbodbc.readthedocs.io/en/latest/pages/getting_started.html#establish-a-connection-with-your-database)):

```
>>> from turbodbc import connect
>>> connection = connect(driver="PostgreSQL",
...                      server="hostname",
...                      port="5432",
...                      database="myDataBase",
...                      uid="myUsername",
...                      pwd="myPassword")
```

I guess this is what you are looking for? If you really want to have a function that creates a connection string and nothing else, you could use https://github.com/blue-yonder/turbodbc/blob/master/python/turbodbc/connect.py#L12, but this function is not part of the public interface and might change any second, though I would not expect it to.

If you try to build an SQLAlchemy dialect for some database, you might want to take a look at the Exasol dialect: https://github.com/blue-yonder/sqlalchemy_exasol/blob/master/sqlalchemy_exasol/turbodbc.py

Also, check out the list of SQLAlchemy dialects with turbodbc support before creating a new one, although I can't say anything about the quality/usage of these: http://turbodbc.readthedocs.io/en/latest/pages/faq.html#can-i-use-turbodbc-together-with-sqlalchemy

**Comment by paolof89** [comment]
Thank you so much, I'll check all your links.
I close the issue.
