### ISSUE TITLE
Cannot retrieve VARCHAR(max) for MSSQL

### ISSUE THREAD

**Issue by MathMagique** [blue-yonder/turbodbc#122]
With turbodbc 2.1.0, you cannot retrieve results of `VARCHAR(max)` columns on MSSQL databases. Consider the following code:
```
>>> from turbodbc import connect, make_options
>>> options = make_options(prefer_unicode=True)
>>> connection = connect(dsn="MSSQL", uid="***", pwd="***", turbodbc_options=options)
>>> cursor = connection.cursor()
>>> cursor.execute("CREATE TABLE test_max (a VARCHAR(max))")
>>> cursor.execute("INSERT INTO test_max VALUES ('hi')")
>>> cursor.execute("SELECT * FROM test_max").fetchall()
[]
```
The expected result would be `[[u'hi']]`.

Also, if the `prefer_unicode` option is set to `False`, the return value changes to
```
[[u'']]
```
which is also not correct.

**Comment by MathMagique** [comment]
@paolof89 That should resolve your problem you reported in the comments of #64 as well.

**Comment by sevetseh28** [comment]
Hi. Something similar is happening to me. 
I have running:
- Ubuntu 16.04
- Official MS Driver (v13.1)
- Python 2.7.9
- turbodbc 2.1.0
Im connecting to an Azure DB with latin-1 charset.
All the inserts are done correctly and no encoding problems but when I retrieve results with from a nvarchar column I get u'\x00\x00\x00\x00\x00\x00\x00\x00\x00.............' on each row.
Changing prefer_unicode option does not fix it.

This does NOT happen if I use FreeTDS driver though. 

Thanks

**Comment by MathMagique** [comment]
Hi @sevetseh28! I was also able to reproduce your issue using `NVARCHAR(max)`. It was indeed the same issue in another flavour.

I have provided a fix and a new configuration option `varchar_max_character_limit` that allows to specify what to do for such fields. The current default is to fetch the first `65535` characters and truncate anything that comes after.

If you think this default value is excessive, it is still possible to change it prior to the release I plan for sometime this weekend. Changes after the release would constitute a breaking change, so if you have concerns please raise them now.

**Comment by paolof89** [comment]
Should we suggest an update to the [Dirk Jonker's SQLAlchemy](https://github.com/dirkjonker/sqlalchemy-turbodbc/blob/master/sqlalchemy_turbodbc/connector.py#L90) module?

**Comment by MathMagique** [comment]
It is not really a requirement as the bug should disappear automatically. But I guess Dirk would love some feedback and being able to set the option may be valuable to some users, so why not?
