### ISSUE TITLE
Build Arrow Support on Windows

### ISSUE THREAD

**Issue by xhochy** [blue-yonder/turbodbc#128]
Currently we only build and test it on Linux and macOS

**Comment by gabomgp** [comment]
Yes please... i'm testing turbodbc to extract a large table from SQL Server (10 billion records) to Arrow. Then, the plan is to load the arrow data to Postgresql, but filtering rows and maybe not all columns, etc. But, i'm doing it from Windows. ¿Is good idea to use turbodbc for this scenario?

**Comment by MathMagique** [comment]
Hi @gabomgp! 10 billion rows is quite something, and I assume that you do not want to load everything into memory at once. This is what the arrow support currently does, though a batched version is on the horizon (#133). Windows support will come soon, I hope.

If you plan to filter out columns and rows, I'd recommend to do that on the database with an appropriate SQL query. If you do not really need arrow support, but just a fast means to get data from your database, try turbodbc's [support for NumPy](http://turbodbc.readthedocs.io/en/latest/pages/advanced_usage.html#numpy-support) that also supports batches.

Be warned, though, that PostgreSQL's open source ODBC driver performs poorly, and you may be better off using psycopg2 or asyncpg for inserting data. You would then use a turbodbc cursor to iterate over your MSSQL server result set and pass it to asyncpg's `executemany()` function.

**Comment by gabomgp** [comment]
Thanks you, I'll try with psycopg2.
