### ISSUE TITLE
Add option to fetch optimal integer type for a column using Arrow

### ISSUE THREAD

**Issue by xhochy** [blue-yonder/turbodbc#129]
Instead of always fetching a column as INT64, we could also return the smallest possible integer type that suits for a column. This might not be the fastest, but the most memory efficient one.

**Comment by MathMagique** [comment]
Good point, this would also affect the classic Python and NumPy frontends.

**Comment by xhochy** [comment]
In a first shot, the implementation with Arrow will be much simpler as there already exists code for that in Arrow itself.

**Comment by MathMagique** [comment]
Well, it is not a big deal to create a 32 bit integer NumPy array, and converting a 32 bit integer to Python integers is not that hard either ;-).

**Comment by xhochy** [comment]
Small clarification: This issue is about to provide a special option to the Arrow backend that returns the smallest possible integer type based on the data.
