### ISSUE TITLE
NaN objects in object columns of pandas dataframes from read_csv()

### ISSUE THREAD

**Issue by mmoeddel** [blue-yonder/turbodbc#130]
When trying to use `executemanycolumns()` with a pandas dataframe like this:

```
df = pd.read_csv(localfilepath,compression=csvfmt.compression,header=csvfmt.headerline,sep=csvdialect.delimiter,quotechar=csvdialect.quotechar,quoting=csvdialect.quoting,encoding=csvfmt.encoding,infer_datetime_format=True)

#some datetime conversion here

TURBODBC_OPTIONS = turbodbc.make_options(read_buffer_size=turbodbc.Megabytes(100),
                                                         parameter_sets_to_buffer=20000)
connection = turbodbc.connect(dsn=dsn, turbodbc_options=TURBODBC_OPTIONS)
cursor_local = connection.cursor()

to_insert = [(c, v) for c, v in df.iteritems()]
columns = [v.values for _, v in to_insert]
query = "INSERT INTO {}.{} ({}) VALUES ({})".format(schema,table,','.join([c for c, _ in to_insert]),
                                                                 ','.join(['?' for _, _ in to_insert]))
cursor.executemanycolumns(query,columns)
```

I get `RuntimeError: Unable to cast Python instance to C++ type (complie in debug mode for details)`.

The issue turned out to be that `read_csv()`represents missing strings as `NaN`objects in `object`columns rather than `None`objects.

It would be great if turbodbc could deal with those directly.

**Comment by MathMagique** [comment]
Hi @mmoeddel! Thanks for reporting, I would consider this a bug in turbodbc although I do not agree with the way NumPy/Pandas flags missing values ;-).

**Comment by xhochy** [comment]
Note that `pyarrow.Table.from_pandas()` takes care of this speciality and thus we should be able to handle these columns with https://github.com/blue-yonder/turbodbc/pull/125

**Comment by MathMagique** [comment]
Arrow parameters are available for a while now, and they take care of the Pandas oddities pretty well. Thus, I will not invest extra time to keep up with Pandas, but delegate this to the Arrow people.

**Comment by danielurencio** [comment]
I get this error with version 3.0.0 even when installing pyarrow first.

**This installation of turbodbc does not support Apache Arrow extensions. Please install the `pyarrow` package. If you have built turbodbc from source, you may also need to reinstall turbodbc to compile the extensions.**
