### ISSUE TITLE
is there any reason to use turbodbc with Postgresql? vs psycopg2

### ISSUE THREAD

**Issue by seanv507** [blue-yonder/turbodbc#132]
I didn't see anywhere in the documentation why one should use turbodbc for postgresql or mysql... it seems to suggest that native drivers are better than odbc and psycopg2 is a native driver?

**Comment by MathMagique** [comment]
Hi there! For PostgreSQL, reasons to use turbodbc are limited as the official PostgreSQL ODBC driver is very slow. The [turbodbc documentation](http://turbodbc.readthedocs.io/en/latest/pages/databases/postgresql.html) suggests psycopg2 and asyncpg as quicker alternatives.

Turbodbc just gives you the fastest ODBC based alternative when there is no native driver or the native driver does not perform well. Native is not necessarily better, as it depends on the amount of love that has been put into it.

I have heard of turbodbc users that prefer turbodbc over alternatives for MySQL, though I have no benchmark results to support that.

**Comment by seanv507** [comment]
Thanks its clear now. I had seen that  documentation,but it confused me...I
thought it meant that psycopg2 also provided an odbc wrapper which one
could use with turbodbc, and then it was fast...
Sean
