### ISSUE TITLE
adding support for generating batches of arrow tables

### ISSUE THREAD

**Issue by thenomemac** [blue-yonder/turbodbc#133]
I'm writing a CLI using turbdodbc's arrow support to dump the arrow arrays to disk as parquet files... I'm interested in contributed support to batch "K" rows of large tables this will allow for tables larger than memory. Would there be an easy path forward for adding this feature. Maybe I'm missing something but seems like there should be a fetcharrowbatch() method?

**Comment by MathMagique** [comment]
Hi there! That sounds like a useful project of yours, and the feature you suggest makes perfect sense. There should be a `fetcharrowbatches()` similar to the existing `fetchnumpybatches()` that you can use for your tool.

**Comment by MathMagique** [comment]
Done in #172
