### ISSUE TITLE
Conda packages for odbc drivers

### ISSUE THREAD

**Issue by kszucs** [blue-yonder/turbodbc#136]
Hi!

There is an ongoing PR https://github.com/ibis-project/ibis/pull/999 about integrating turbodbc in ibis. To make installing odbc drivers easier, I've suggested to create conda-forge packages.

However I'm familiar with conda, but not with installing drivers. 
What do You think about making odbc drivers available through conda forge? 
Most of the time it's about downloading a prebuilt library, am I right?
Would You help us creating/maintaining such packages?

**Comment by MathMagique** [comment]
Hi Krisztián!

Thanks for your patience, I was on vacation and could not reply earlier. Distributing ODBC drivers via conda sounds like a great idea. This would also solve issues around different versions of unixodbc/iodbc on the host system and the conda environment.

ODBC drivers are usually distributed via one of the following methods:
* Packages that come with the operating system. Examples: MySQL and PostgreSQL drivers on most Linux systems, MSSQL ODBC driver on Windows
* Installers/packages that contain ODBC drivers for installation with/without adminstrator rights. Examples: MSSQL ODBC drivers on Linux
* Source packages that contain code for compilation with your system's ODBC headers. Examples: Many open source DBs, including MySQL, PostgreSQL, ...

Maintaining conda packages may be a legal hassle depending on the driver's license. The best solution would be to convince as many package maintainers/companies as possible that providing Conda packages for their driver is a good idea.

I could try to convince the Exasol company to supply their Exasolution ODBC drivers as Conda packages, and I would be willing to invest limited time in that. For other drivers, I am afraid I will not be able to justify the time investment to my employer, and I will not be sufficiently motivated to do it in my spare time (seeing I do not use these databases or can use the existing packages).

I am sorry for not providing the answer you may have hoped for.
