### ISSUE TITLE
Add Python 3 compatibility

### ISSUE THREAD

**Issue by FlorianWilhelm** [blue-yonder/turbodbc#14]
Developing new libraries with no Python 3 compatibility doesn't help our cause. 
Python 3 is the future and the future starts now ;-)

**Comment by MathMagique** [comment]
Python 2.7 is a good start ;-). But I agree that Python 3 support makes for a brilliant feature.

**Comment by bluesmoon** [comment]
We are unable to use python 2.7 due to other dependencies on 3.4.

Also, attempting to install on 3.4 gives the following error:

```
Collecting turbodbc
  Downloading turbodbc-0.5.0.tar.gz (48kB)
    100% |################################| 51kB 6.8MB/s 
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-ib5tsr84/turbodbc/setup.py", line 42, in <module>
        _remove_strict_prototype_option_from_distutils_config()
      File "/tmp/pip-build-ib5tsr84/turbodbc/setup.py", line 38, in _remove_strict_prototype_option_from_distutils_config
        for key, value in config.iteritems():
    AttributeError: 'dict' object has no attribute 'iteritems'
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-ib5tsr84/turbodbc/
```

Might be useful to at the very least provide a better error message.

**Comment by MathMagique** [comment]
@bluesmoon I guess there are a few things I have to fix for Python 3. Hopefully, I will be able to work on Python 3 support next week. Just improving the error message is not something I will be content with ;-).

**Comment by FlorianWilhelm** [comment]
Really cool!
