### ISSUE TITLE
Exception when trying to execute a cursor when connected to Clickhouse DB

### ISSUE THREAD

**Issue by nvm1** [blue-yonder/turbodbc#144]
Hi there,

I'm trying to retrieve data from our Clickhouse DB, but unfortunatelly have some troubles.
Connection works fine, but when I try to execute a cursor I get the following exception:

>  File "C:\Anaconda\lib\site-packages\turbodbc\cursor.py", line 135, in execute
>     self.impl.prepare(sql)
> turbodbc_intern.Error: ODBC error
> state: IM001
> native error code: 0
> message: [Microsoft][ODBC Driver Manager] Driver does not support this function
> Error during rollback: Obtaining diagnostic record from unixODBC handle failed

Had to comment the decorator on line 121 to get to the error, but unfortunatelly can't get any further on it. 

The code:

```
import turbodbc

connection = turbodbc.connect(dsn='clickhouse_dsn')
cursor = connection.cursor()
cursor.execute('SELECT 1') # Fails right here
```

**Comment by MathMagique** [comment]
Hi! Clickhouse - never heard of that one ;-). Does Clickhouse come with a dedicated ODBC driver? It might help to enable ODBC driver tracing, if the driver supports this option (most drivers/driver managers do). This would generate a list of commands that is sent to the driver, and might provide an indication as to what went wrong. Please make sure that the trace log does not contain credentials ;-).

**Comment by nvm1** [comment]
Well, It's not that I know Clickhouse for a long time either, but it seems to be quite fast :)
Please, see the log for a couple of selects in the attachment. Didn't find any credentials in there, hope it's alright :)

[SQL.LOG](https://github.com/blue-yonder/turbodbc/files/1659042/SQL.LOG)

if it helps somehow: I was able to use pyodbc instead of turbodbc, but I couldn't use the same instance of cursor, so for every new sql I had to go with `connection.cursor().execute(SQL)`

**Comment by MathMagique** [comment]
@nvm1 Thanks for sharing the logs! The interesting bit is
```
python          2054-288c	EXIT  SQLNumParams  with return code -1 (SQL_ERROR)
		HSTMT               0x0000008660AB9020
		SWORD *             0x000000866095E7A0

		DIAG [IM001] [Microsoft][ODBC Driver Manager] Driver does not support this function (0) 
```
The `SQLNumParams` function returns an error, the driver apparently does not support [this feature](https://docs.microsoft.com/en-us/sql/odbc/reference/syntax/sqlnumparams-function). This is in violation of the ODBC [core interface conformance](https://docs.microsoft.com/en-us/sql/odbc/reference/develop-app/core-interface-conformance):

> All ODBC drivers must exhibit at least Core-level interface conformance. Because the features in the Core level are those required by most generic interoperable applications, the driver can work with such applications. The features in the Core level also correspond to the features defined in the ISO CLI specification and to the nonoptional features defined in the Open Group CLI specification.
> [...]
> Handle dynamic parameters, including arrays of parameters, in the input direction only, by calling SQLBindParameter and SQLNumParams. (Parameters in the output direction are feature 203 in Level 2 Interface Conformance.)

I would suggest to report the missing support for `SQLNumParams` to the creators of the ODBC driver you use. Turbodbc relies on (input) parameters being supported, and it would be difficult and defeating the purpose of turbodbc to be compatible with drivers that do not support parameters. I will have to close this issue as "won't fix"/

**Comment by nvm1** [comment]
Thank you for the explanation!
I've reported the issue, hope they can do something about that
https://github.com/yandex/clickhouse-odbc/issues/53
