### ISSUE TITLE
cursor.nextset() does not exist in turbodbc

### ISSUE THREAD

**Issue by jackalhan** [blue-yonder/turbodbc#145]
Hi,

Ubuntu 16.04
Python 3.6.4
Driver: FreeTDS
turbODBC 2.5.0
SQL Server Database
 
I have a proc in db where I can receive multiple result sets per execute. While I was using pyodbc, I was able to read all result sets by calling cursor.nextset(), but when I switch to turbodbc, I could not find any similar function therefore it throws me the following error 

> 'Cursor' object has no attribute 'nextset'

Thanks

**Comment by MathMagique** [comment]
Hi! Yes, the optional `nextset()` method from PEP-249 is not implemented yet. I'll put it on the list.

**Comment by jackalhan** [comment]
Thank you so much.

**Comment by stevesimmons** [comment]
Would `nextset()` be straightforward to implement in Turbodbc for MS SQL Server?

The equivalent code in `pyodbc` is at L1760 of [cursor.cpp](https://github.com/mkleehammer/pyodbc/blob/969ea2c42712036d473fab5d4db715452580c6d3/src/cursor.cpp#L1760), and essentially just calls SQL Server's [SQLMoreResults()](https://docs.microsoft.com/en-us/sql/odbc/reference/syntax/sqlmoreresults-function?view=sql-server-ver15) function.

**Comment by stevesimmons** [comment]
It looks like the back-end C++ machinery is already done. We only need to expose the C++ function call to Python.

More specifically:
* `statement.cpp` already has `more_results()` calling `raii_statement::do_more_results()`.
* On the Python side, in `cursor.py`, need to define a `Cursor.nextset()` method, calling `Cursor.impl.more_results()`.
* In `cpp/turbodbc_python/Library/src/python_bindings/cursor.cpp`, need to add a line like:    
  `.def("more_results", &turbodbc::cursor::more_results())`

Can anyone try this quickly? I am on Windows and am having trouble compiling this...

**Comment by adavis-vvp** [comment]
Has this functionality been added? I need to run this as well.

**Comment by david-engelmann** [comment]
This should be closed out due to #369
