### ISSUE TITLE
PEP343 conformance

### ISSUE THREAD

**Issue by AtomBaf** [blue-yonder/turbodbc#149]
Hi blueyonder

It would be nice to be able to have a [PEP343 ](https://www.python.org/dev/peps/pep-0343/) compliant turbodbc connection.

This way, I could write something like:
`
with turbodbc.connect('...') as conn:
`

Thank you for your useful and great project

**Comment by MathMagique** [comment]
Hi there! Makes sense to me, and I have the feeling that this would make for a nice and easy contribution :-).
