### ISSUE TITLE
Q: Is there a way to use this with ORMs, such as SQLAlchemy?

### ISSUE THREAD

**Issue by MaximilianR** [blue-yonder/turbodbc#15]
This looks awesome.

Is it as simple as swapping out a connection string for our existing `pyodbc` string?
`connection_string = 'mssql+pyodbc:///?odbc_connect=%s' % connect_str` 
We're currently using a FreeTDS driver, would we change that?

Thanks

**Comment by MathMagique** [comment]
Hi!

Thanks for the question. SQLAlchemy support has not landed yet, so it is not that easy yet.

BUT: My colleague @bjoernmeier already put some work in that. He has even created a pull request for https://github.com/blue-yonder/sqlalchemy_exasol/pull/50, a project which adds a dialect for the Exasolution database. It is probably not as general as one would wish, but it is a start.

**Comment by MathMagique** [comment]
You would definitely keep your existing FreeTDS driver, though.

**Comment by MathMagique** [comment]
Short update: The pull request I mentioned above has been accepted.

**Comment by dirkjonker** [comment]
I'll try creating a SQLAlchemy dialect for mssql + turbodbc, should be fairly trivial, (except perhaps for unicode data).

**Comment by MathMagique** [comment]
@dirkjonker That would be really awesome! The unicode stuff needs fixing on the turbodbc side, obviously. You could have a look at the codebase of https://github.com/blue-yonder/sqlalchemy_exasol for inspiration. I am not really familiar with that code base, but I suspect a little cargo culting in there ;-).

If you encounter turbodbc issues, please keep reporting them :-)

**Comment by dirkjonker** [comment]
Status update on the MSSQL + turbodbc dialect. It works in certain situations but there are still some weird cases with "invalid cursor state" errors and situations where SQLAlchemy is calling rollback without an active transaction, which also raises errors. Those can probably be solved in the dialect, but I'll report if it's actually turbodbc that is causing problems.

As soon as I have something that works reasonably well I'll release an alpha version under MIT license, should be somewhere this week.

**Comment by MathMagique** [comment]
That sounds great!

**Comment by dirkjonker** [comment]
Took me a bit longer than expected (priorities, learning C, etc.) but I have created a very simple SQLAlchemy dialect for turbodbc + SQL Server.

https://github.com/dirkjonker/sqlalchemy-turbodbc

Feel free to fork/clone/whatever.

**Comment by MathMagique** [comment]
Excellent news @dirkjonker! Good job!

If you want, you could create a pull request to include a small SQLAlchemy section in the Readme that mentions your efforts and those at https://github.com/blue-yonder/sqlalchemy_exasol. Otherwise I will just add the note myself :-).

**Comment by dirkjonker** [comment]
@MathMagique of course! Here you go: https://github.com/blue-yonder/turbodbc/pull/66

**Comment by MathMagique** [comment]
Since the answer to this question is now part of the Readme, and there is initial support for MSSQL with SQLAlchemy, I'll mark this question as resolved.
