### ISSUE TITLE
Segfault when double arrow-fetching result

### ISSUE THREAD

**Issue by chmp** [blue-yonder/turbodbc#152]
After calling `fetcharrow` multiple times, the python process crashing when calling `to_pandas`. A minimal example is:

```python
c = conn.cursor()
c.execute('select * from data')

c.fetchallarrow()
c.fetchallarrow().to_pandas()
```

To my surpirse, it seems the call to `to_pandas` is required for the crash to happen. Running the following code does not result in a crash:

```python
c = conn.cursor()
c.execute('select * from data')

print(len(c.fetchallarrow()))
print(len(c.fetchallarrow()))
print(len(c.fetchallarrow()))
# output:
# 100000
# 0
# 0
```

The table `test_data` was created with

```python
df = pd.DataFrame({'i': np.random.randint(0, 128, size=100_000) })
df.to_sql('test_data', engine)
```

While I assume calling `fetchallarrow()` multiple times is not supported, my preference would be to either return an empty dataframe or to raise a python exception.

Versions:

```python
print(turbodbc.__version__)  # 2.5.0
print(arrow.__version__)  # 0.12.1
print(pd.__version__)  # 0.22.0
```

CC. @xhochy

**Comment by chmp** [comment]
For completeness: the corresponding `fetchallnumpy` code works just fine (giving an empty dataframe):

```python
c = conn.cursor()
c.execute('select * from data')

pd.DataFrame(c.fetchallnumpy())
pd.DataFrame(c.fetchallnumpy())
```

**Comment by xhochy** [comment]
Yes, this is an Arrow bug on converting empty tables to Dataframes. This is fixed in Arrow master and will come with the next release

**Comment by chmp** [comment]
Ah strange. Because I did test `pyarrow.Table.from_pandas(pd.DataFrame({'i': []})).to_pandas()` which works. Ok in that case. I guess I'll close the ticket.
