### ISSUE TITLE
Problem with dates in Teradata

### ISSUE THREAD

**Issue by Alexndrrr** [blue-yonder/turbodbc#157]
I am using turbodbc to load data from Netezza to Teradata, in batches. My first field is a date called `PAID_THROUGH_DATE` which is 2017-12-31 for every row. Here's what is looks like as a numpy masked array:

```
('PAID_THROUGH_DATE', masked_array(data=[datetime.date(2017, 12, 31),
                   datetime.date(2017, 12, 31),
                   datetime.date(2017, 12, 31), ...,
                   datetime.date(2017, 12, 31),
                   datetime.date(2017, 12, 31),
                   datetime.date(2017, 12, 31)],
             mask=[False, False, False, ..., False, False, False],
       fill_value=numpy.datetime64('NaT'),
            dtype='datetime64[D]'))
```

  I am receiving this error during the insert:

```
File "C:/.../sql_to_td.py", line 127, in test_turbo_numpy
    cur.execute(insert_query, batch_data)

  File "C:\...\turbodbc\exceptions.py", line 52, in wrapper
    raise DatabaseError(str(e))

DatabaseError: ODBC error
state: 22008
native error code: -2666
message: [Teradata][ODBC Teradata Driver][Teradata Database] Invalid date supplied for LOAD_TEST.PAID_THROUGH_DATE.
```

I'm using:
- turbodbc 2.6.0
- python 3.6.4 64-bit
- Windows 7
- Teradata Database ODBC Driver 16.10

I'm getting the same error with both the "AAA" (ANSI) format and "III" (integer) format for DateTime in the DSN options. I've also tried both ANSI mode and Teradata mode, always getting the same error.

Here's a little more detail going in to Event Viewer:

```
[Teradata][ODBC Teradata Driver] Invalid argument
HY096
[Teradata][ODBC Teradata Driver] Invalid Attribute
HY092
[Teradata][ODBC Teradata Driver][Teradata Database] Invalid date supplied for LOAD_TEST.PAID_THROUGH_DATE. 
22008
```

Any idea what's going on?

**Comment by MathMagique** [comment]
Hi! That may be a bit difficult for me to debug, as I neither have access to Netezza nor Teradata :joy:. It might be helpful to have the piece of code to handle the querying/inserting parts.

To circle in on the error, please try the following with your Teradata cursor:

```
cursor.execute("INSERT INTO LOAD_TEST (PAID_THROUGH_DATE) VALUES (?)", [datetime.date(2017, 12, 31)])
```

That should establish a baseline whether inserting any dates works at all. If that works, try inserting a hand-crafted NumPy array of dates. Then try a masked array of dates. Then try a masked array of dates that also includes masked values.

Enable Teradata's ODBC tracing (I'm pretty sure it has an option like this somewhere in the ODBC driver settings). The ODBC trace log may contain extra pointers as to what goes wrong.

My suspicion is that _somewhere_ in the data set, there is a date that is not considered a valid date by Teradata.

**Comment by Alexndrrr** [comment]
This was my fault. I was using `cur.execute` rather than `cur.executemanycolumns`.

Here's the successful code:
```
src_con = turbo.connect(dsn='IDS_LAB')
data = src_con.cursor()
data.execute(source_query)
con = turbo.connect(dsn='TD', autocommit=False)
cur = con.cursor()
for batch_data in data.fetchnumpybatches():
    cur.executemanycolumns(insert_query, batch_data.values())
```

**Comment by MathMagique** [comment]
Glad you found it! Seeing that you are using two databases that I am not familiar with, I would love to get some feedback regarding turbodbc's performance. A baseline of how you did things without turbodbc would be interesting as well :-)

**Comment by Alexndrrr** [comment]
Well Teradata is new to me and the company so we don't have a baseline yet. I'm still experimenting with various ways to load data on to our shiny new server. But so far turbodbc is the clear winner, I'm able to get about 30k records/minute with it, compared to 15k using the Teradata library. pyodbc is so slow I gave up waiting for it. I haven't played with SSIS or Teradata's proprietary tools though, they may still beat turbodbc.

As all our stuff is being migrated from Netezza to Teradata, I'm not sure I'll be able to test data flow in the other direction, but I'd be interested to see how turbodbc compares to Netezza's built in ability to read and write csv files. I haven't found any method even close in speed to that.

**Comment by MathMagique** [comment]
Thanks for sharing your results 💪, and good luck with the rest of your migration! If you encounter any more obstacles, just open an issue :-).
