### ISSUE TITLE
Replacement for sqoop

### ISSUE THREAD

**Issue by albertoRamon** [blue-yonder/turbodbc#159]
makes sense replacement the typical batch task?:
"Export last partition from MySQL/SQL Server to Parquet on HDFS Cluster"

With Turbodbc + Arrow to parquet

**Comment by MathMagique** [comment]
Hi Alberto! I think it is worth a shot. The invest on your side is rather low (setup ODBC environment, small program with `fetchallarrow` and the necessary Arrow to Parquet writing), and the gains _could_ be substantial, depending on how sqoop (that I am not familiar with) attaches to your databases.

**Comment by MathMagique** [comment]
@albertoRamon Would you like to share any results that you may have found?

**Comment by albertoRamon** [comment]
I will work in background, any progress / doubt will be notified in this issue
I think the first step is mount a docker compose with  MySQL/Postgress and Arrow + Turbodbc preferably using Alpine
The idea is mount this ingestion/conversion as service on PaaS
