### ISSUE TITLE
Confusion about cursor.commit()

### ISSUE THREAD

**Issue by newtux** [blue-yonder/turbodbc#163]
I'm not sure if this is a bug, oversight, or something I'm doing wrong. 

From the documentation [here](http://turbodbc.readthedocs.io/en/latest/pages/advanced_usage.html#autocommit) it looks to me like I'm supposed to be able to call `cursor.commit()` to commit changes. However, I always get the error:

```
    cursor.commit()
AttributeError: 'Cursor' object has no attribute 'commit'
```
The main [transaction documentation](http://turbodbc.readthedocs.io/en/latest/pages/getting_started.html#transactions) only has documenation using the connection. 
 
Looking at https://github.com/blue-yonder/turbodbc/blob/master/python/turbodbc/cursor.py I also don't see a commit method. Am I missing something?

**Comment by MathMagique** [comment]
Sorry, the documentation is wrong. Please call `connection.commit()`.

**Comment by MathMagique** [comment]
Fixed the documentation.

**Comment by viewler** [comment]
> 

thanks dude, you helped me ❤️
