### ISSUE TITLE
executemanycolumns cause InterfaceError  UTF-16 Strings are not supported yet when use pyarrow table as parameter

### ISSUE THREAD

**Issue by ericksc** [blue-yonder/turbodbc#165]
Trying 
cursor.executemanycolumns("INSERT INTO my_table VALUES (?, ?,?, ?, ?, ?, ?, ?,?)", table)

My_table looks like:
![image](https://user-images.githubusercontent.com/20059518/39946260-c1a2c210-552a-11e8-9c26-64302dac3155.png)

 I got the following error:
  File "/opt/anaconda/lib/python3.6/site-packages/turbodbc/exceptions.py", line 54, in wrapper
    raise InterfaceError(str(e))
turbodbc.exceptions.InterfaceError: UTF-16 Strings are not supported yet

___________
turbodbc: 2.6.0
Python 3.6
anaconda
MS SQL server
running under linux opensuse

**Comment by ericksc** [comment]
please note I am using 
options = make_options(parameter_sets_to_buffer=1000,prefer_unicode=True)

**Comment by MathMagique** [comment]
Hi! Yeah, UTF-16 support is currently missing for pyarrow extensions. They should work for the Numpy extensions, however.

**Comment by xhochy** [comment]
This will be fixed by https://github.com/blue-yonder/turbodbc/pull/190
