### ISSUE TITLE
Geting garbled up characters (e.g., u'\xe2\x99\xa5') when options = make_options(prefer_unicode=True) on MS SQL server

### ISSUE THREAD

**Issue by ericksc** [blue-yonder/turbodbc#166]
Getting query results looks like:
'n\x00v\x00a\x00r\x00c\x00h\x00a\x00r\x00'

**Comment by MathMagique** [comment]
Could you provide a code example and more details about your settings and the queried DB and table, please?

**Comment by ericksc** [comment]
Hi @MathMagique , I'll provide you the code example. In this case, it is when the connection is trying to get a pyarrow table.

**Comment by MathMagique** [comment]
Ah, ok, that probably already explains it. The arrow support does not have support for Unicode yet for neither results nor parameters, see your other thing #165. The numpy support should work for both result sets and parameters as expected.

**Comment by xhochy** [comment]
This should be fixed by https://github.com/blue-yonder/turbodbc/pull/190
