### ISSUE TITLE
Fetching as Arrow in batches

### ISSUE THREAD

**Issue by ah-** [blue-yonder/turbodbc#168]
First off, turbodbc is fantastic 👍, thanks for building it!

Do you have any plans to implement fetching data as Arrow in batches?

My use case is similar to https://github.com/blue-yonder/turbodbc/issues/159, I want to fetch data and write out parquet, and holding the entire dataset in memory is inconvenient. So it would be really nice to have an Arrow equivalent of `fetchnumpybatches`.

**Comment by MathMagique** [comment]
Thanks! There are no concrete plans today, but I agree that it would be a useful feature.
