### ISSUE TITLE
fletcher support

### ISSUE THREAD

**Issue by dhirschfeld** [blue-yonder/turbodbc#173]
It might be very nice to support https://github.com/xhochy/fletcher, especially if it allowed for zero-copy construction of pandas DataFrames.

**Comment by xhochy** [comment]
This will probably come naturally once we have a working release of `fletcher`. There we will implement functions to convert Arrow Tables to/from fletcher-filled Pandas DataFrames.

**Comment by MathMagique** [comment]
In this case, is it ok to close this issue here?

**Comment by dhirschfeld** [comment]
Sure, I'll close for now and follow in fletcher. If any changes need to be made in turbodbc I can always reopen...
