### ISSUE TITLE
can't pickle turbodbc_intern.Options objects

### ISSUE THREAD

**Issue by raghuveernaraharisetti** [blue-yonder/turbodbc#178]
turbodbc_intern.Options is not pickable, it would be cool if all the turbodbc objects are pickable.
which the makes it possible to use with multiprocessing module.

error message:

Traceback (most recent call last):
  File "C:\Python36_64\lib\multiprocessing\queues.py", l
    obj = _ForkingPickler.dumps(obj)
  File "C:\Python36_64\lib\multiprocessing\reduction.py"
    cls(buf, protocol).dump(obj)
TypeError: can't pickle turbodbc_intern.Options objects

**Comment by MathMagique** [comment]
The options object would only be the first object to pickle. I also wonder what pickling would mean for an open connection/cursor object, as these have inherent state that is basically impossible to pickle (database state). I do not know you concrete use case, but you could pickle the dictionary that would be passed to the `make_options()` and continue from there. You should not share a `Connection` or `Cursor` object among threads/processes anyways.

**Comment by raghuveernaraharisetti** [comment]
you were right, turns out I was trying to pickle the object which is holding an active connection instance.
Thanks for your help!
