### ISSUE TITLE
nonfree odbc

### ISSUE THREAD

**Issue by yaxxie** [blue-yonder/turbodbc#188]
This is going to be a tough one for you guys but I thought I'd put it out there anyway: 

When I've tried a couple of non-free odbc connectors, of those that actually work at all (devart ones), the python process segfaults when turbodbc tries to use them. Able to fetch fine however using pyodbc (tried postgres and CSV odbc connector).

**Comment by xhochy** [comment]
@yaxxie When there is a segfault, would you be able to provide us with a (C++) stacktrace? You can strip out the parts of the closed source driver but the turbodbc part might already be helpful to us.

**Comment by yaxxie** [comment]
oddly enough I can't reproduce this; will close. Sorry!
