### ISSUE TITLE
cursor.fetchallarrow() raise an error

### ISSUE THREAD

**Issue by shamzos** [blue-yonder/turbodbc#200]
Hello When I excuted : 

`table = cursor.fetchallarrow()`

it raised : 
```
TypeError: make_arrow_result_set(): incompatible function arguments. The following argument types are supported:
    1. (arg0: turbodbc::result_sets::result_set, arg1: bool, arg2: bool) -> turbodbc_arrow_support.ArrowResultSet

Invoked with: <turbodbc_intern.BaseResultSet object at 0x0000020DCB9166C0>, False, False
```

Windows 10, teradata SQL, python 3.5

thank you.

**Comment by MathMagique** [comment]
The current release of turbodbc does not support Arrow on Windows systems. The next release will change that. For a workaround, you could try to make do with the Numpy features; those are supported on Windows also by the current release.

**Comment by shamzos** [comment]
I have a question about performance and time execution using "arrow", is it the same as using Numpy? 
thank you.

**Comment by MathMagique** [comment]
Timings are comparable and for some applications within the margin of error. Arrow has advantages when handling strings due to built-in dictionary encoding and also allows for fast transformation into pandas data frames. Still, Numpy support is quite up to the game.

**Comment by shamzos** [comment]
thanks for the clarification. 
I wish you the best.
