### ISSUE TITLE
Not able install in Ubuntu 18.04 with pip

### ISSUE THREAD

**Issue by bsnithin44** [blue-yonder/turbodbc#215]
I am not being able to install turbodbc package with pip. I get the following error and [output.txt](https://github.com/blue-yonder/turbodbc/files/3289536/output.txt)

![pip error](https://user-images.githubusercontent.com/22328816/59492096-d709c300-8ea5-11e9-8878-a63e931f2e32.JPG)

However, I am able to install it with conda-forge, 

Can you please tell me how to install it with pip. I need to install it with pip because I want to use it for AWS lambda. I am not sure if they support conda-forge packages and how to add it to zip file which AWS lambda takes.

**Comment by bsnithin44** [comment]
Downgrading to pip 9.0.3 worked.

**Comment by v4ld3rr4m4** [comment]
I solved problem in Fedora29 installing boost-devel

**sudo dnf install boost-devel**
