### ISSUE TITLE
Access Raw SQL type information

### ISSUE THREAD

**Issue by synapticarbors** [blue-yonder/turbodbc#225]
I am experimenting with converting some legacy code which used IOPro to fetch data from a MySQL DB into numpy, to turbodbc, and ran into the following issue. In IOPro, when you used `cursor.fetchdictarray()`, you'd get back a structured numpy array where the dtype of the individual columns closely matched the sql type. So for example, a `smallint` would map to `np.int16`, `int` to `np.int32`, and `varchar` fields would become a fixed-sized string of `len(varchar) + 1` to account for the null string termination. 

I can see that turbodbc generically maps all MySQL integer types to `np.int64`, floats to `np.float64` and string-like fields to `object` types. 

I was wondering if there was any way to either:

1. Recapitulate the IOPro behavior directly (seems unlikely),
2. Get access to the raw underlying types without making separate queries of the database. This information does not seem to be in `cursor.description`, which just has the simple generic types defined in `cpp/turbodbc/Library/turbodbc/type_code.h`.

Due to our particular usage that accesses a row at a time (usually by mapping the numpy structured array to a C-array of structs with Cython), having compact rows is typically a lot more performant for us. I can certainly take turbodbc's output and convert it into the what IOPro provides by default, but I just wanted to make sure there weren't any facilities built into turbodbc that I was missing.

**Comment by MathMagique** [comment]
Hi! Unfortunately, there is no secret capability that you are missing, neither 1 nor 2. I planned to add support for more type codes to get the smallest possible type. Due to time limitations I never got around to do it.

You could still end up winning some time even without the conversion due to efficient use of batched I/O operations. Might be worth a try.
