### ISSUE TITLE
install error:

### ISSUE THREAD

**Issue by ieipi** [blue-yonder/turbodbc#234]
the error message is like:

$pip install turbodbc
Collecting turbodbc
  Using cached https://files.pythonhosted.org/packages/c9/a7/afbfb0a788259243867a5cc9efe4bd40c836a8e5776c1f04269a774913a6/turbodbc-3.3.0.tar.gz
Requirement already satisfied: pybind11>=2.2.0 in /home/acct/anaconda3/lib/python3.7/site-packages (from turbodbc) (2.4.3)
Requirement already satisfied: six in /home/acct/anaconda3/lib/python3.7/site-packages (from turbodbc) (1.12.0)
Building wheels for collected packages: turbodbc
  Building wheel for turbodbc (setup.py) ... error
  Complete output from command /home/acct/anaconda3/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-oc83bal5/turbodbc/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d /tmp/pip-wheel-s5sn0cj5 --python-tag cp37:
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib.linux-x86_64-3.7
  creating build/lib.linux-x86_64-3.7/turbodbc
  copying turbodbc/constructors.py -> build/lib.linux-x86_64-3.7/turbodbc
  copying turbodbc/exceptions.py -> build/lib.linux-x86_64-3.7/turbodbc
  copying turbodbc/connect.py -> build/lib.linux-x86_64-3.7/turbodbc
  copying turbodbc/__init__.py -> build/lib.linux-x86_64-3.7/turbodbc
  copying turbodbc/api_constants.py -> build/lib.linux-x86_64-3.7/turbodbc
  copying turbodbc/connection.py -> build/lib.linux-x86_64-3.7/turbodbc
  copying turbodbc/cursor.py -> build/lib.linux-x86_64-3.7/turbodbc
  copying turbodbc/options.py -> build/lib.linux-x86_64-3.7/turbodbc
  copying turbodbc/data_types.py -> build/lib.linux-x86_64-3.7/turbodbc
  running egg_info
  writing turbodbc.egg-info/PKG-INFO
  writing dependency_links to turbodbc.egg-info/dependency_links.txt
  writing requirements to turbodbc.egg-info/requires.txt
  writing top-level names to turbodbc.egg-info/top_level.txt
  reading manifest file 'turbodbc.egg-info/SOURCES.txt'
  reading manifest template 'MANIFEST.in'
  writing manifest file 'turbodbc.egg-info/SOURCES.txt'
  running build_ext
  building 'libturbodbc' extension
  creating build/temp.linux-x86_64-3.7
  creating build/temp.linux-x86_64-3.7/src
  creating build/temp.linux-x86_64-3.7/src/cpp_odbc
  creating build/temp.linux-x86_64-3.7/src/cpp_odbc/level2
  creating build/temp.linux-x86_64-3.7/src/cpp_odbc/level1
  creating build/temp.linux-x86_64-3.7/src/cpp_odbc/level3
  creating build/temp.linux-x86_64-3.7/src/turbodbc
  creating build/temp.linux-x86_64-3.7/src/turbodbc/result_sets
  creating build/temp.linux-x86_64-3.7/src/turbodbc/field_translators
  creating build/temp.linux-x86_64-3.7/src/turbodbc/descriptions
  creating build/temp.linux-x86_64-3.7/src/turbodbc/parameter_sets
  gcc -pthread -B /home/acct/anaconda3/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -fPIC -Iinclude/ -I/home/acct/anaconda3/include -I/home/acct/anaconda3/include/python3.7m -c src/cpp_odbc/multi_value_buffer.cpp -o build/temp.linux-x86_64-3.7/src/cpp_odbc/multi_value_buffer.o --std=c++11
  gcc -pthread -B /home/acct/anaconda3/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -fPIC -Iinclude/ -I/home/acct/anaconda3/include -I/home/acct/anaconda3/include/python3.7m -c src/cpp_odbc/connection.cpp -o build/temp.linux-x86_64-3.7/src/cpp_odbc/connection.o --std=c++11
  gcc -pthread -B /home/acct/anaconda3/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -fPIC -Iinclude/ -I/home/acct/anaconda3/include -I/home/acct/anaconda3/include/python3.7m -c src/cpp_odbc/statement.cpp -o build/temp.linux-x86_64-3.7/src/cpp_odbc/statement.o --std=c++11
  gcc -pthread -B /home/acct/anaconda3/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -fPIC -Iinclude/ -I/home/acct/anaconda3/include -I/home/acct/anaconda3/include/python3.7m -c src/cpp_odbc/make_environment.cpp -o build/temp.linux-x86_64-3.7/src/cpp_odbc/make_environment.o --std=c++11
  gcc -pthread -B /home/acct/anaconda3/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -fPIC -Iinclude/ -I/home/acct/anaconda3/include -I/home/acct/anaconda3/include/python3.7m -c src/cpp_odbc/error.cpp -o build/temp.linux-x86_64-3.7/src/cpp_odbc/error.o --std=c++11
  gcc -pthread -B /home/acct/anaconda3/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -fPIC -Iinclude/ -I/home/acct/anaconda3/include -I/home/acct/anaconda3/include/python3.7m -c src/cpp_odbc/column_description.cpp -o build/temp.linux-x86_64-3.7/src/cpp_odbc/column_description.o --std=c++11
  gcc -pthread -B /home/acct/anaconda3/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -fPIC -Iinclude/ -I/home/acct/anaconda3/include -I/home/acct/anaconda3/include/python3.7m -c src/cpp_odbc/environment.cpp -o build/temp.linux-x86_64-3.7/src/cpp_odbc/environment.o --std=c++11
  gcc -pthread -B /home/acct/anaconda3/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -fPIC -Iinclude/ -I/home/acct/anaconda3/include -I/home/acct/anaconda3/include/python3.7m -c src/cpp_odbc/cpp_odbc.cpp -o build/temp.linux-x86_64-3.7/src/cpp_odbc/cpp_odbc.o --std=c++11
  gcc -pthread -B /home/acct/anaconda3/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -fPIC -Iinclude/ -I/home/acct/anaconda3/include -I/home/acct/anaconda3/include/python3.7m -c src/cpp_odbc/level2/input_string_buffer.cpp -o build/temp.linux-x86_64-3.7/src/cpp_odbc/level2/input_string_buffer.o --std=c++11
  gcc -pthread -B /home/acct/anaconda3/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -fPIC -Iinclude/ -I/home/acct/anaconda3/include -I/home/acct/anaconda3/include/python3.7m -c src/cpp_odbc/level2/u16string_buffer.cpp -o build/temp.linux-x86_64-3.7/src/cpp_odbc/level2/u16string_buffer.o --std=c++11
  gcc -pthread -B /home/acct/anaconda3/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -fPIC -Iinclude/ -I/home/acct/anaconda3/include -I/home/acct/anaconda3/include/python3.7m -c src/cpp_odbc/level2/handles.cpp -o build/temp.linux-x86_64-3.7/src/cpp_odbc/level2/handles.o --std=c++11
  gcc -pthread -B /home/acct/anaconda3/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -fPIC -Iinclude/ -I/home/acct/anaconda3/include -I/home/acct/anaconda3/include/python3.7m -c src/cpp_odbc/level2/api.cpp -o build/temp.linux-x86_64-3.7/src/cpp_odbc/level2/api.o --std=c++11
  gcc -pthread -B /home/acct/anaconda3/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -fPIC -Iinclude/ -I/home/acct/anaconda3/include -I/home/acct/anaconda3/include/python3.7m -c src/cpp_odbc/level2/input_u16string_buffer.cpp -o build/temp.linux-x86_64-3.7/src/cpp_odbc/level2/input_u16string_buffer.o --std=c++11
  gcc -pthread -B /home/acct/anaconda3/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -fPIC -Iinclude/ -I/home/acct/anaconda3/include -I/home/acct/anaconda3/include/python3.7m -c src/cpp_odbc/level2/level1_connector.cpp -o build/temp.linux-x86_64-3.7/src/cpp_odbc/level2/level1_connector.o --std=c++11
  src/cpp_odbc/level2/level1_connector.cpp:17:28: fatal error: boost/locale.hpp: No such file or directory
   #include <boost/locale.hpp>
                              ^
  compilation terminated.
  error: command 'gcc' failed with exit status 1
  
  ----------------------------------------
  Failed building wheel for turbodbc
  Running setup.py clean for turbodbc
Failed to build turbodbc
Installing collected packages: turbodbc
  Running setup.py install for turbodbc ... error
    Complete output from command /home/acct/anaconda3/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-oc83bal5/turbodbc/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-record-ii5c6e0e/install-record.txt --single-version-externally-managed --compile:
    running install
    running build
    running build_py
    creating build
    creating build/lib.linux-x86_64-3.7
    creating build/lib.linux-x86_64-3.7/turbodbc
    copying turbodbc/constructors.py -> build/lib.linux-x86_64-3.7/turbodbc
    copying turbodbc/exceptions.py -> build/lib.linux-x86_64-3.7/turbodbc
    copying turbodbc/connect.py -> build/lib.linux-x86_64-3.7/turbodbc
    copying turbodbc/__init__.py -> build/lib.linux-x86_64-3.7/turbodbc
    copying turbodbc/api_constants.py -> build/lib.linux-x86_64-3.7/turbodbc
    copying turbodbc/connection.py -> build/lib.linux-x86_64-3.7/turbodbc
    copying turbodbc/cursor.py -> build/lib.linux-x86_64-3.7/turbodbc
    copying turbodbc/options.py -> build/lib.linux-x86_64-3.7/turbodbc
    copying turbodbc/data_types.py -> build/lib.linux-x86_64-3.7/turbodbc
    running egg_info
    writing turbodbc.egg-info/PKG-INFO
    writing dependency_links to turbodbc.egg-info/dependency_links.txt
    writing requirements to turbodbc.egg-info/requires.txt
    writing top-level names to turbodbc.egg-info/top_level.txt
    reading manifest file 'turbodbc.egg-info/SOURCES.txt'
    reading manifest template 'MANIFEST.in'
    writing manifest file 'turbodbc.egg-info/SOURCES.txt'
    running build_ext
    building 'libturbodbc' extension
    creating build/temp.linux-x86_64-3.7
    creating build/temp.linux-x86_64-3.7/src
    creating build/temp.linux-x86_64-3.7/src/cpp_odbc
    creating build/temp.linux-x86_64-3.7/src/cpp_odbc/level2
    creating build/temp.linux-x86_64-3.7/src/cpp_odbc/level1
    creating build/temp.linux-x86_64-3.7/src/cpp_odbc/level3
    creating build/temp.linux-x86_64-3.7/src/turbodbc
    creating build/temp.linux-x86_64-3.7/src/turbodbc/result_sets
    creating build/temp.linux-x86_64-3.7/src/turbodbc/field_translators
    creating build/temp.linux-x86_64-3.7/src/turbodbc/descriptions
    creating build/temp.linux-x86_64-3.7/src/turbodbc/parameter_sets
    gcc -pthread -B /home/acct/anaconda3/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -fPIC -Iinclude/ -I/home/acct/anaconda3/include -I/home/acct/anaconda3/include/python3.7m -c src/cpp_odbc/multi_value_buffer.cpp -o build/temp.linux-x86_64-3.7/src/cpp_odbc/multi_value_buffer.o --std=c++11
    gcc -pthread -B /home/acct/anaconda3/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -fPIC -Iinclude/ -I/home/acct/anaconda3/include -I/home/acct/anaconda3/include/python3.7m -c src/cpp_odbc/connection.cpp -o build/temp.linux-x86_64-3.7/src/cpp_odbc/connection.o --std=c++11
    gcc -pthread -B /home/acct/anaconda3/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -fPIC -Iinclude/ -I/home/acct/anaconda3/include -I/home/acct/anaconda3/include/python3.7m -c src/cpp_odbc/statement.cpp -o build/temp.linux-x86_64-3.7/src/cpp_odbc/statement.o --std=c++11
    gcc -pthread -B /home/acct/anaconda3/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -fPIC -Iinclude/ -I/home/acct/anaconda3/include -I/home/acct/anaconda3/include/python3.7m -c src/cpp_odbc/make_environment.cpp -o build/temp.linux-x86_64-3.7/src/cpp_odbc/make_environment.o --std=c++11
    gcc -pthread -B /home/acct/anaconda3/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -fPIC -Iinclude/ -I/home/acct/anaconda3/include -I/home/acct/anaconda3/include/python3.7m -c src/cpp_odbc/error.cpp -o build/temp.linux-x86_64-3.7/src/cpp_odbc/error.o --std=c++11
    gcc -pthread -B /home/acct/anaconda3/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -fPIC -Iinclude/ -I/home/acct/anaconda3/include -I/home/acct/anaconda3/include/python3.7m -c src/cpp_odbc/column_description.cpp -o build/temp.linux-x86_64-3.7/src/cpp_odbc/column_description.o --std=c++11
    gcc -pthread -B /home/acct/anaconda3/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -fPIC -Iinclude/ -I/home/acct/anaconda3/include -I/home/acct/anaconda3/include/python3.7m -c src/cpp_odbc/environment.cpp -o build/temp.linux-x86_64-3.7/src/cpp_odbc/environment.o --std=c++11
    gcc -pthread -B /home/acct/anaconda3/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -fPIC -Iinclude/ -I/home/acct/anaconda3/include -I/home/acct/anaconda3/include/python3.7m -c src/cpp_odbc/cpp_odbc.cpp -o build/temp.linux-x86_64-3.7/src/cpp_odbc/cpp_odbc.o --std=c++11
    gcc -pthread -B /home/acct/anaconda3/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -fPIC -Iinclude/ -I/home/acct/anaconda3/include -I/home/acct/anaconda3/include/python3.7m -c src/cpp_odbc/level2/input_string_buffer.cpp -o build/temp.linux-x86_64-3.7/src/cpp_odbc/level2/input_string_buffer.o --std=c++11
    gcc -pthread -B /home/acct/anaconda3/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -fPIC -Iinclude/ -I/home/acct/anaconda3/include -I/home/acct/anaconda3/include/python3.7m -c src/cpp_odbc/level2/u16string_buffer.cpp -o build/temp.linux-x86_64-3.7/src/cpp_odbc/level2/u16string_buffer.o --std=c++11
    gcc -pthread -B /home/acct/anaconda3/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -fPIC -Iinclude/ -I/home/acct/anaconda3/include -I/home/acct/anaconda3/include/python3.7m -c src/cpp_odbc/level2/handles.cpp -o build/temp.linux-x86_64-3.7/src/cpp_odbc/level2/handles.o --std=c++11
    gcc -pthread -B /home/acct/anaconda3/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -fPIC -Iinclude/ -I/home/acct/anaconda3/include -I/home/acct/anaconda3/include/python3.7m -c src/cpp_odbc/level2/api.cpp -o build/temp.linux-x86_64-3.7/src/cpp_odbc/level2/api.o --std=c++11
    gcc -pthread -B /home/acct/anaconda3/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -fPIC -Iinclude/ -I/home/acct/anaconda3/include -I/home/acct/anaconda3/include/python3.7m -c src/cpp_odbc/level2/input_u16string_buffer.cpp -o build/temp.linux-x86_64-3.7/src/cpp_odbc/level2/input_u16string_buffer.o --std=c++11
    gcc -pthread -B /home/acct/anaconda3/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -fPIC -Iinclude/ -I/home/acct/anaconda3/include -I/home/acct/anaconda3/include/python3.7m -c src/cpp_odbc/level2/level1_connector.cpp -o build/temp.linux-x86_64-3.7/src/cpp_odbc/level2/level1_connector.o --std=c++11
    src/cpp_odbc/level2/level1_connector.cpp:17:28: fatal error: boost/locale.hpp: No such file or directory
     #include <boost/locale.hpp>
                                ^
    compilation terminated.
    error: command 'gcc' failed with exit status 1
    
    ----------------------------------------
Command "/home/acct/anaconda3/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-oc83bal5/turbodbc/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-record-ii5c6e0e/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-install-oc83bal5/turbodbc/

**Comment by fjetter** [comment]
Looks like you're missing the necessary boost libraries, see https://turbodbc.readthedocs.io/en/latest/pages/getting_started.html#linux-and-osx and make sure these requirements are properly set up on your system

Otherwise I can highly recommend to use `conda` which should take care of these issues.
