### ISSUE TITLE
Installing turbodbc on Windows 10/Python3.7 with VS 2019

### ISSUE THREAD

**Issue by keitherskine** [blue-yonder/turbodbc#236]
I'm having trouble installing turbodbc on a Windows 10 (Pro) laptop, with Python 3.7 (64-bit), and using VS 2019 build tools (not VS 2015).  When running "pip install turbodbc", I originally got the error "Cannot open include file: 'boost/locale.hpp': No such file or directory", so I downloaded BOOST (version 1.72), unzipped it, and set BOOST_ROOT accordingly.  On the next install attempt, the script got a bit further but failed with the following error:

```
    C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.24.28314\bin\HostX86\x64\link.exe /nologo /INCREMENTAL:NO /LTCG /DLL /MANIFEST:EMBED,ID=2 /MANIFESTUAC:NO /LIBPATH:build\lib.win-amd64-3.7 /LIBPATH:C:\Users\toast\Downloads\boost_1_72_0\boost_1_72_0\stage\lib /LIBPATH:C:\Users\toast\Downloads\boost_1_72_0\boost_1_72_0\lib64-msvc-14.0 "/LIBPATH:c:\users\toast\documents\talks\odbc parameters\pyvenv1\libs" /LIBPATH:C:\Users\toast\AppData\Local\Programs\Python\Python37\libs /LIBPATH:C:\Users\toast\AppData\Local\Programs\Python\Python37 "/LIBPATH:c:\users\toast\documents\talks\odbc parameters\pyvenv1\PCbuild\amd64" "/LIBPATH:C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.24.28314\lib\x64" "/LIBPATH:C:\Program Files (x86)\Windows Kits\10\lib\10.0.18362.0\ucrt\x64" "/LIBPATH:C:\Program Files (x86)\Windows Kits\10\lib\10.0.18362.0\um\x64" odbc32.lib /EXPORT:PyInit_turbodbc_intern build\temp.win-amd64-3.7\Release\src\cpp_odbc\column_description.obj build\temp.win-amd64-3.7\Release\src\cpp_odbc\connection.obj build\temp.win-amd64-3.7\Release\src\cpp_odbc\cpp_odbc.obj build\temp.win-amd64-3.7\Release\src\cpp_odbc\environment.obj build\temp.win-amd64-3.7\Release\src\cpp_odbc\error.obj build\temp.win-amd64-3.7\Release\src\cpp_odbc\make_environment.obj build\temp.win-amd64-3.7\Release\src\cpp_odbc\multi_value_buffer.obj build\temp.win-amd64-3.7\Release\src\cpp_odbc\statement.obj build\temp.win-amd64-3.7\Release\src\cpp_odbc\level1\api.obj build\temp.win-amd64-3.7\Release\src\cpp_odbc\level1\level1.obj build\temp.win-amd64-3.7\Release\src\cpp_odbc\level1\unixodbc_backend.obj build\temp.win-amd64-3.7\Release\src\cpp_odbc\level1\unixodbc_backend_debug.obj build\temp.win-amd64-3.7\Release\src\cpp_odbc\level2\api.obj build\temp.win-amd64-3.7\Release\src\cpp_odbc\level2\handles.obj build\temp.win-amd64-3.7\Release\src\cpp_odbc\level2\input_string_buffer.obj build\temp.win-amd64-3.7\Release\src\cpp_odbc\level2\input_u16string_buffer.obj build\temp.win-amd64-3.7\Release\src\cpp_odbc\level2\level1_connector.obj build\temp.win-amd64-3.7\Release\src\cpp_odbc\level2\level2.obj build\temp.win-amd64-3.7\Release\src\cpp_odbc\level2\string_buffer.obj build\temp.win-amd64-3.7\Release\src\cpp_odbc\level2\u16string_buffer.obj build\temp.win-amd64-3.7\Release\src\cpp_odbc\level3\level3.obj build\temp.win-amd64-3.7\Release\src\cpp_odbc\level3\raii_connection.obj build\temp.win-amd64-3.7\Release\src\cpp_odbc\level3\raii_environment.obj build\temp.win-amd64-3.7\Release\src\cpp_odbc\level3\raii_statement.obj build\temp.win-amd64-3.7\Release\src\turbodbc\buffer_size.obj build\temp.win-amd64-3.7\Release\src\turbodbc\column.obj build\temp.win-amd64-3.7\Release\src\turbodbc\command.obj build\temp.win-amd64-3.7\Release\src\turbodbc\configuration.obj build\temp.win-amd64-3.7\Release\src\turbodbc\connect.obj build\temp.win-amd64-3.7\Release\src\turbodbc\connection.obj build\temp.win-amd64-3.7\Release\src\turbodbc\cursor.obj build\temp.win-amd64-3.7\Release\src\turbodbc\description.obj build\temp.win-amd64-3.7\Release\src\turbodbc\errors.obj build\temp.win-amd64-3.7\Release\src\turbodbc\field_translator.obj build\temp.win-amd64-3.7\Release\src\turbodbc\make_description.obj build\temp.win-amd64-3.7\Release\src\turbodbc\make_field_translator.obj build\temp.win-amd64-3.7\Release\src\turbodbc\parameter.obj build\temp.win-amd64-3.7\Release\src\turbodbc\string_helpers.obj build\temp.win-amd64-3.7\Release\src\turbodbc\time_helpers.obj build\temp.win-amd64-3.7\Release\src\turbodbc\descriptions\boolean_description.obj build\temp.win-amd64-3.7\Release\src\turbodbc\descriptions\date_description.obj build\temp.win-amd64-3.7\Release\src\turbodbc\descriptions\floating_point_description.obj build\temp.win-amd64-3.7\Release\src\turbodbc\descriptions\integer_description.obj build\temp.win-amd64-3.7\Release\src\turbodbc\descriptions\string_description.obj build\temp.win-amd64-3.7\Release\src\turbodbc\descriptions\timestamp_description.obj build\temp.win-amd64-3.7\Release\src\turbodbc\descriptions\unicode_description.obj build\temp.win-amd64-3.7\Release\src\turbodbc\field_translators\boolean_translator.obj build\temp.win-amd64-3.7\Release\src\turbodbc\field_translators\date_translator.obj build\temp.win-amd64-3.7\Release\src\turbodbc\field_translators\float64_translator.obj build\temp.win-amd64-3.7\Release\src\turbodbc\field_translators\int64_translator.obj build\temp.win-amd64-3.7\Release\src\turbodbc\field_translators\string_translator.obj build\temp.win-amd64-3.7\Release\src\turbodbc\field_translators\timestamp_translator.obj build\temp.win-amd64-3.7\Release\src\turbodbc\parameter_sets\bound_parameter_set.obj build\temp.win-amd64-3.7\Release\src\turbodbc\parameter_sets\field_parameter_set.obj build\temp.win-amd64-3.7\Release\src\turbodbc\parameter_sets\set_field.obj build\temp.win-amd64-3.7\Release\src\turbodbc\result_sets\bound_result_set.obj build\temp.win-amd64-3.7\Release\src\turbodbc\result_sets\double_buffered_result_set.obj build\temp.win-amd64-3.7\Release\src\turbodbc\result_sets\field_result_set.obj build\temp.win-amd64-3.7\Release\src\turbodbc\result_sets\result_set.obj build\temp.win-amd64-3.7\Release\src\turbodbc\result_sets\row_based_result_set.obj build\temp.win-amd64-3.7\Release\src\turbodbc_python\determine_parameter_type.obj build\temp.win-amd64-3.7\Release\src\turbodbc_python\python_parameter_set.obj build\temp.win-amd64-3.7\Release\src\turbodbc_python\python_result_set.obj build\temp.win-amd64-3.7\Release\src\turbodbc_python\python_bindings\buffer_size.obj build\temp.win-amd64-3.7\Release\src\turbodbc_python\python_bindings\column_info.obj build\temp.win-amd64-3.7\Release\src\turbodbc_python\python_bindings\connect.obj build\temp.win-amd64-3.7\Release\src\turbodbc_python\python_bindings\connection.obj build\temp.win-amd64-3.7\Release\src\turbodbc_python\python_bindings\cursor.obj build\temp.win-amd64-3.7\Release\src\turbodbc_python\python_bindings\error.obj build\temp.win-amd64-3.7\Release\src\turbodbc_python\python_bindings\module.obj build\temp.win-amd64-3.7\Release\src\turbodbc_python\python_bindings\options.obj build\temp.win-amd64-3.7\Release\src\turbodbc_python\python_bindings\python_parameter_set.obj build\temp.win-amd64-3.7\Release\src\turbodbc_python\python_bindings\python_result_set.obj /OUT:build\lib.win-amd64-3.7\turbodbc_intern.cp37-win_amd64.pyd /IMPLIB:build\temp.win-amd64-3.7\Release\src\cpp_odbc\turbodbc_intern.cp37-win_amd64.lib
    LINK : fatal error LNK1104: cannot open file 'libboost_locale-vc142-mt-x64-1_72.lib'
    error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\BuildTools\\VC\\Tools\\MSVC\\14.24.28314\\bin\\HostX86\\x64\\link.exe' failed with exit status 1104
```

A couple of questions to make sure I'm on the right track:
1) I noticed in PyPi (https://pypi.org/project/turbodbc/#files), there is only one file, a source tar file.  Should there be some wheels in there as well?
2) Do you happen to know if turbodbc can be installed with VS 2019 build tools?  It's the same major version number as VS 2015 (version 14), so I was hoping it would be OK.

Any and all help is greatly appreciated.

**Comment by xhochy** [comment]
Can you post more of the log? It should work with VS 2019, not tested but there shouldn't be a major change breaking our support.

For the wheels: There were Windows wheels in previous versions but the release process broke. Happy to accept PRs but if you want to have binary releases of turbodbc, conda packages are available and work reliably.

**Comment by keitherskine** [comment]
Here is the whole log @xhochy .  Meanwhile, thank you for the conda suggestion, I will explore that approach.

[turbodbc_install_log.txt](https://github.com/blue-yonder/turbodbc/files/4021281/turbodbc_install_log.txt)

**Comment by keitherskine** [comment]
Just FYI, I did manage to install turbodbc in the end using the VS 2019 C++ compiler (but without installing Visual Studio).  For reference, here's what I did:

1. Download the VS 2019 build tools from https://visualstudio.microsoft.com/downloads/#build-tools-for-visual-studio-2019, and install the "C++ build tools" Workload.
2. Download boost from https://www.boost.org/ (click on the "Current Release" version link, in my case "Version 1.72.0", then download the Windows zip file).
3. Unzip the zipfile somewhere on your PC.
4. In a command prompt, navigate to the boost top-level directory.
5. Run `.\bootstrap.bat` (this generates the `b2` executable)
6. Run `.\b2` (this generates the `stage` directory and contents, takes a few minutes to run)
7. Set the BOOST_ROOT env variable with something like
`set BOOST_ROOT=C:\your\path\to\boost\boost_1_72_0\boost_1_72_0`
8. Run `pip install turbodbc`

**Comment by clsack** [comment]
Had the same issue, solved it with @keitherskine suggestion. Thank you so much!

**Comment by kumardurgesh91** [comment]
Solution by @keitherskine worked for me but getting another error when trying to connect to Mariadb DB.

Traceback (most recent call last):
  File "D:/PythonDbPractice/db.py", line 1, in <module>
    from turbodbc import connect
  File "D:\PythonDbPractice\venv\lib\site-packages\turbodbc\__init__.py", line 4, in <module>
    from .connect import connect
  File "D:\PythonDbPractice\venv\lib\site-packages\turbodbc\connect.py", line 6, in <module>
    from turbodbc_intern import connect as intern_connect
ImportError: DLL load failed while importing turbodbc_intern: A dynamic link library (DLL) initialization routine failed.

**I have tried these 3 different approach but getting same error.**

```
connection = connect(
            dsn='mariadb-python'
        )
```

        ```
connection = connect(
            connection_string='Driver={MariaDB ODBC 3.1 Driver};Server=127.0.0.1;Port=3306;Database=python_db;Uid=root;Pwd=;')
```


        ```
connection = connect(
        server ='127.0.0.1',
        database ='python_db',
        uid ='root',
        pwd ='',
        port =3306,
        driver ='MariaDB ODBC 3.1 Driver')
```

new in python, Thanks for any help.

**Comment by keitherskine** [comment]
I don't know exactly what the problem is @kumardurgesh91 , but it may be an issue of 32-bit Python versus 64-bit Python.  The turbodbc docs [suggest](https://turbodbc.readthedocs.io/en/latest/pages/getting_started.html#windows) that turbodbc works only with 64-bit Python.  If your current Python version is 32-bit (check with `python -VV`), you might want to try installing 64-bit Python and then re-installing turbodbc.

**Comment by willsthompson** [comment]
I had this problem on Windows Server 2012 R2, even after following the steps suggested in @keitherskine's [comment](https://github.com/blue-yonder/turbodbc/issues/236#issuecomment-570792316). For some reason the Boost libraries built in the `/stage` directory did not match what was expected by `turbodbc`'s build script. I was eventually able to get it to compile by downloading pre-compiled Boost binaries. Specifically:

1. Download and run the MSVC 14.2-generated build installer ([boost_1_73_0-msvc-14.2-64.exe](https://sourceforge.net/projects/boost/files/boost-binaries/1.73.0/boost_1_73_0-msvc-14.2-64.exe/download)) from https://sourceforge.net/projects/boost/files/boost-binaries/1.73.0/
2. Rename `/boost_1_73_0/lib64-msvc-14.2` to `/boost_1_73_0/stage/lib`
3. Follow @keitherskine's [steps 7 and 8 from above](https://github.com/blue-yonder/turbodbc/issues/236#issuecomment-570792316).
