### ISSUE TITLE
Apache Arrow result sets

### ISSUE THREAD

**Issue by xhochy** [blue-yonder/turbodbc#24]
In line with `turbodbc_numpy` it would be helpful to also have a `turbodbc_arrow` library that will produce Apache Arrow Tables / RecordBatches.

**Comment by MathMagique** [comment]
That seems very promising, in particular to open up turbodbc for many tools that already rely or plan to use arrow.

**Comment by yaxxie** [comment]
When this gets released, will we bump to 1.2.0?

**Comment by MathMagique** [comment]
I plan to bump to 2.0.0 and adpot semantic versioning from then on. I will also make a breaking change for the deprecation I introduced with `make_options()`.

**Comment by yaxxie** [comment]
Even better 👍 Thanks!
