### ISSUE TITLE
Issues installing turbodbc with pip

### ISSUE THREAD

**Issue by aricbeaver** [blue-yonder/turbodbc#243]
I've read through these two posts but they seem unreleated but through the same error:
https://github.com/blue-yonder/turbodbc/issues/179
https://github.com/blue-yonder/turbodbc/issues/120

I've confirmed I am running 64 bit python 3.7. And the second resolution with the wheels that were pushed to pipy in 2018.

Any suggestions why turbodbc fails to install? Thanks.

Error message:
`src\cpp_odbc\level2\level1_connector.cpp(17): fatal error C1083: Cannot open include file: 'boost/locale.hpp': No such file or directory
    error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\BuildTools\\VC\\Tools\\MSVC\\14.24.28314\\bin\\HostX64\\x64\\cl.exe' failed with exit status 2`

Full log:
`Collecting turbodbc
  Using cached turbodbc-3.3.0.tar.gz (78 kB)
Requirement already satisfied: pybind11>=2.2.0 in c:\users\fg376t\appdata\local\programs\python\python37\lib\site-packages (from turbodbc) (2.4.3)
Requirement already satisfied: six in c:\users\fg376t\appdata\local\programs\python\python37\lib\site-packages (from turbodbc) (1.12.0)
Installing collected packages: turbodbc
    Running setup.py install for turbodbc ... error
    ERROR: Command errored out with exit status 1:
     command: 'c:\users\fg376t\appdata\local\programs\python\python37\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\fg376t\\AppData\\Local\\Temp\\pip-install-hapojomw\\turbodbc\\setup.py'"'"'; __file__='"'"'C:\\Users\\fg376t\\AppData\\Local\\Temp\\pip-install-hapojomw\\turbodbc\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\fg376t\AppData\Local\Temp\pip-record-b91qwtho\install-record.txt' --single-version-externally-managed --compile --install-headers 'c:\users\fg376t\appdata\local\programs\python\python37\Include\turbodbc'
         cwd: C:\Users\fg376t\AppData\Local\Temp\pip-install-hapojomw\turbodbc\
    Complete output (76 lines):
    warning: BOOST_ROOT enviroment variable not set
    running install
    running build
    running build_py
    creating build
    creating build\lib.win-amd64-3.7
    creating build\lib.win-amd64-3.7\turbodbc
    copying turbodbc\api_constants.py -> build\lib.win-amd64-3.7\turbodbc
    copying turbodbc\connect.py -> build\lib.win-amd64-3.7\turbodbc
    copying turbodbc\connection.py -> build\lib.win-amd64-3.7\turbodbc
    copying turbodbc\constructors.py -> build\lib.win-amd64-3.7\turbodbc
    copying turbodbc\cursor.py -> build\lib.win-amd64-3.7\turbodbc
    copying turbodbc\data_types.py -> build\lib.win-amd64-3.7\turbodbc
    copying turbodbc\exceptions.py -> build\lib.win-amd64-3.7\turbodbc
    copying turbodbc\options.py -> build\lib.win-amd64-3.7\turbodbc
    copying turbodbc\__init__.py -> build\lib.win-amd64-3.7\turbodbc
    running egg_info
    writing turbodbc.egg-info\PKG-INFO
    writing dependency_links to turbodbc.egg-info\dependency_links.txt
    writing requirements to turbodbc.egg-info\requires.txt
    writing top-level names to turbodbc.egg-info\top_level.txt
    reading manifest file 'turbodbc.egg-info\SOURCES.txt'
    reading manifest template 'MANIFEST.in'
    writing manifest file 'turbodbc.egg-info\SOURCES.txt'
    running build_ext
    building 'turbodbc_intern' extension
    creating build\temp.win-amd64-3.7
    creating build\temp.win-amd64-3.7\Release
    creating build\temp.win-amd64-3.7\Release\src
    creating build\temp.win-amd64-3.7\Release\src\cpp_odbc
    creating build\temp.win-amd64-3.7\Release\src\cpp_odbc\level1
    creating build\temp.win-amd64-3.7\Release\src\cpp_odbc\level2
    creating build\temp.win-amd64-3.7\Release\src\cpp_odbc\level3
    creating build\temp.win-amd64-3.7\Release\src\turbodbc
    creating build\temp.win-amd64-3.7\Release\src\turbodbc\descriptions
    creating build\temp.win-amd64-3.7\Release\src\turbodbc\field_translators
    creating build\temp.win-amd64-3.7\Release\src\turbodbc\parameter_sets
    creating build\temp.win-amd64-3.7\Release\src\turbodbc\result_sets
    creating build\temp.win-amd64-3.7\Release\src\turbodbc_python
    creating build\temp.win-amd64-3.7\Release\src\turbodbc_python\python_bindings
    C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.24.28314\bin\HostX64\x64\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MD -Iinclude/ -Ic:\users\fg376t\appdata\local\programs\python\python37\Include -Ic:\users\fg376t\appdata\local\programs\python\python37\include -Ic:\users\fg376t\appdata\local\programs\python\python37\include "-IC:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.24.28314\Include" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\shared" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\um" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\winrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\ucrt" /EHsc /Tpsrc\cpp_odbc\column_description.cpp /Fobuild\temp.win-amd64-3.7\Release\src\cpp_odbc\column_description.obj -DNOMINMAX
    column_description.cpp
    C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.24.28314\bin\HostX64\x64\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MD -Iinclude/ -Ic:\users\fg376t\appdata\local\programs\python\python37\Include -Ic:\users\fg376t\appdata\local\programs\python\python37\include -Ic:\users\fg376t\appdata\local\programs\python\python37\include "-IC:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.24.28314\Include" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\shared" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\um" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\winrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\ucrt" /EHsc /Tpsrc\cpp_odbc\connection.cpp /Fobuild\temp.win-amd64-3.7\Release\src\cpp_odbc\connection.obj -DNOMINMAX
    connection.cpp
    C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.24.28314\bin\HostX64\x64\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MD -Iinclude/ -Ic:\users\fg376t\appdata\local\programs\python\python37\Include -Ic:\users\fg376t\appdata\local\programs\python\python37\include -Ic:\users\fg376t\appdata\local\programs\python\python37\include "-IC:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.24.28314\Include" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\shared" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\um" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\winrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\ucrt" /EHsc /Tpsrc\cpp_odbc\cpp_odbc.cpp /Fobuild\temp.win-amd64-3.7\Release\src\cpp_odbc\cpp_odbc.obj -DNOMINMAX
    cpp_odbc.cpp
    C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.24.28314\bin\HostX64\x64\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MD -Iinclude/ -Ic:\users\fg376t\appdata\local\programs\python\python37\Include -Ic:\users\fg376t\appdata\local\programs\python\python37\include -Ic:\users\fg376t\appdata\local\programs\python\python37\include "-IC:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.24.28314\Include" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\shared" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\um" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\winrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\ucrt" /EHsc /Tpsrc\cpp_odbc\environment.cpp /Fobuild\temp.win-amd64-3.7\Release\src\cpp_odbc\environment.obj -DNOMINMAX
    environment.cpp
    C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.24.28314\bin\HostX64\x64\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MD -Iinclude/ -Ic:\users\fg376t\appdata\local\programs\python\python37\Include -Ic:\users\fg376t\appdata\local\programs\python\python37\include -Ic:\users\fg376t\appdata\local\programs\python\python37\include "-IC:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.24.28314\Include" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\shared" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\um" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\winrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\ucrt" /EHsc /Tpsrc\cpp_odbc\error.cpp /Fobuild\temp.win-amd64-3.7\Release\src\cpp_odbc\error.obj -DNOMINMAX
    error.cpp
    C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.24.28314\bin\HostX64\x64\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MD -Iinclude/ -Ic:\users\fg376t\appdata\local\programs\python\python37\Include -Ic:\users\fg376t\appdata\local\programs\python\python37\include -Ic:\users\fg376t\appdata\local\programs\python\python37\include "-IC:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.24.28314\Include" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\shared" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\um" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\winrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\ucrt" /EHsc /Tpsrc\cpp_odbc\make_environment.cpp /Fobuild\temp.win-amd64-3.7\Release\src\cpp_odbc\make_environment.obj -DNOMINMAX
    make_environment.cpp
    C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.24.28314\bin\HostX64\x64\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MD -Iinclude/ -Ic:\users\fg376t\appdata\local\programs\python\python37\Include -Ic:\users\fg376t\appdata\local\programs\python\python37\include -Ic:\users\fg376t\appdata\local\programs\python\python37\include "-IC:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.24.28314\Include" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\shared" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\um" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\winrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\ucrt" /EHsc /Tpsrc\cpp_odbc\multi_value_buffer.cpp /Fobuild\temp.win-amd64-3.7\Release\src\cpp_odbc\multi_value_buffer.obj -DNOMINMAX
    multi_value_buffer.cpp
    C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.24.28314\bin\HostX64\x64\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MD -Iinclude/ -Ic:\users\fg376t\appdata\local\programs\python\python37\Include -Ic:\users\fg376t\appdata\local\programs\python\python37\include -Ic:\users\fg376t\appdata\local\programs\python\python37\include "-IC:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.24.28314\Include" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\shared" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\um" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\winrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\ucrt" /EHsc /Tpsrc\cpp_odbc\statement.cpp /Fobuild\temp.win-amd64-3.7\Release\src\cpp_odbc\statement.obj -DNOMINMAX
    statement.cpp
    C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.24.28314\bin\HostX64\x64\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MD -Iinclude/ -Ic:\users\fg376t\appdata\local\programs\python\python37\Include -Ic:\users\fg376t\appdata\local\programs\python\python37\include -Ic:\users\fg376t\appdata\local\programs\python\python37\include "-IC:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.24.28314\Include" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\shared" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\um" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\winrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\ucrt" /EHsc /Tpsrc\cpp_odbc\level1\api.cpp /Fobuild\temp.win-amd64-3.7\Release\src\cpp_odbc\level1\api.obj -DNOMINMAX
    api.cpp
    C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.24.28314\bin\HostX64\x64\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MD -Iinclude/ -Ic:\users\fg376t\appdata\local\programs\python\python37\Include -Ic:\users\fg376t\appdata\local\programs\python\python37\include -Ic:\users\fg376t\appdata\local\programs\python\python37\include "-IC:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.24.28314\Include" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\shared" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\um" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\winrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\ucrt" /EHsc /Tpsrc\cpp_odbc\level1\level1.cpp /Fobuild\temp.win-amd64-3.7\Release\src\cpp_odbc\level1\level1.obj -DNOMINMAX
    level1.cpp
    C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.24.28314\bin\HostX64\x64\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MD -Iinclude/ -Ic:\users\fg376t\appdata\local\programs\python\python37\Include -Ic:\users\fg376t\appdata\local\programs\python\python37\include -Ic:\users\fg376t\appdata\local\programs\python\python37\include "-IC:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.24.28314\Include" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\shared" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\um" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\winrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\ucrt" /EHsc /Tpsrc\cpp_odbc\level1\unixodbc_backend.cpp /Fobuild\temp.win-amd64-3.7\Release\src\cpp_odbc\level1\unixodbc_backend.obj -DNOMINMAX
    unixodbc_backend.cpp
    C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.24.28314\bin\HostX64\x64\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MD -Iinclude/ -Ic:\users\fg376t\appdata\local\programs\python\python37\Include -Ic:\users\fg376t\appdata\local\programs\python\python37\include -Ic:\users\fg376t\appdata\local\programs\python\python37\include "-IC:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.24.28314\Include" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\shared" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\um" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\winrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\ucrt" /EHsc /Tpsrc\cpp_odbc\level1\unixodbc_backend_debug.cpp /Fobuild\temp.win-amd64-3.7\Release\src\cpp_odbc\level1\unixodbc_backend_debug.obj -DNOMINMAX
    unixodbc_backend_debug.cpp
    C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.24.28314\bin\HostX64\x64\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MD -Iinclude/ -Ic:\users\fg376t\appdata\local\programs\python\python37\Include -Ic:\users\fg376t\appdata\local\programs\python\python37\include -Ic:\users\fg376t\appdata\local\programs\python\python37\include "-IC:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.24.28314\Include" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\shared" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\um" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\winrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\ucrt" /EHsc /Tpsrc\cpp_odbc\level2\api.cpp /Fobuild\temp.win-amd64-3.7\Release\src\cpp_odbc\level2\api.obj -DNOMINMAX
    api.cpp
    C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.24.28314\bin\HostX64\x64\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MD -Iinclude/ -Ic:\users\fg376t\appdata\local\programs\python\python37\Include -Ic:\users\fg376t\appdata\local\programs\python\python37\include -Ic:\users\fg376t\appdata\local\programs\python\python37\include "-IC:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.24.28314\Include" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\shared" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\um" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\winrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\ucrt" /EHsc /Tpsrc\cpp_odbc\level2\handles.cpp /Fobuild\temp.win-amd64-3.7\Release\src\cpp_odbc\level2\handles.obj -DNOMINMAX
    handles.cpp
    C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.24.28314\bin\HostX64\x64\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MD -Iinclude/ -Ic:\users\fg376t\appdata\local\programs\python\python37\Include -Ic:\users\fg376t\appdata\local\programs\python\python37\include -Ic:\users\fg376t\appdata\local\programs\python\python37\include "-IC:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.24.28314\Include" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\shared" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\um" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\winrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\ucrt" /EHsc /Tpsrc\cpp_odbc\level2\input_string_buffer.cpp /Fobuild\temp.win-amd64-3.7\Release\src\cpp_odbc\level2\input_string_buffer.obj -DNOMINMAX
    input_string_buffer.cpp
    C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.24.28314\bin\HostX64\x64\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MD -Iinclude/ -Ic:\users\fg376t\appdata\local\programs\python\python37\Include -Ic:\users\fg376t\appdata\local\programs\python\python37\include -Ic:\users\fg376t\appdata\local\programs\python\python37\include "-IC:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.24.28314\Include" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\shared" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\um" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\winrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\ucrt" /EHsc /Tpsrc\cpp_odbc\level2\input_u16string_buffer.cpp /Fobuild\temp.win-amd64-3.7\Release\src\cpp_odbc\level2\input_u16string_buffer.obj -DNOMINMAX
    input_u16string_buffer.cpp
    C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.24.28314\bin\HostX64\x64\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MD -Iinclude/ -Ic:\users\fg376t\appdata\local\programs\python\python37\Include -Ic:\users\fg376t\appdata\local\programs\python\python37\include -Ic:\users\fg376t\appdata\local\programs\python\python37\include "-IC:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.24.28314\Include" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\shared" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\um" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\winrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\ucrt" /EHsc /Tpsrc\cpp_odbc\level2\level1_connector.cpp /Fobuild\temp.win-amd64-3.7\Release\src\cpp_odbc\level2\level1_connector.obj -DNOMINMAX
    level1_connector.cpp
    src\cpp_odbc\level2\level1_connector.cpp(17): fatal error C1083: Cannot open include file: 'boost/locale.hpp': No such file or directory
    error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\BuildTools\\VC\\Tools\\MSVC\\14.24.28314\\bin\\HostX64\\x64\\cl.exe' failed with exit status 2
    ----------------------------------------
ERROR: Command errored out with exit status 1: 'c:\users\fg376t\appdata\local\programs\python\python37\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\fg376t\\AppData\\Local\\Temp\\pip-install-hapojomw\\turbodbc\\setup.py'"'"'; __file__='"'"'C:\\Users\\fg376t\\AppData\\Local\\Temp\\pip-install-hapojomw\\turbodbc\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\fg376t\AppData\Local\Temp\pip-record-b91qwtho\install-record.txt' --single-version-externally-managed --compile --install-headers 'c:\users\fg376t\appdata\local\programs\python\python37\Include\turbodbc' Check the logs for full command output.`

**Comment by keitherskine** [comment]
You may need to have "boost" unzipped on your PC somewhere and BOOST_ROOT set.  See [this](https://github.com/blue-yonder/turbodbc/issues/236#issuecomment-570792316) comment for more info.

**Comment by aricbeaver** [comment]
That fixed it. One comment is initially I was using VS C++ 14 and it still was not working. Your post seemed to imply it was specific to VS C++19. Thanks!
