### ISSUE TITLE
SQL_SUCCESS_WITH_INFO is treated the same as SQL_ERROR

### ISSUE THREAD

**Issue by pacman82** [blue-yonder/turbodbc#25]
Had a quick look over the c++ part of the implementation and noted that there is a lot of code like this in the library:

```c++
if (return_code == SQL_SUCCESS) {
        return output_handle;
} else {
        throw cpp_odbc::error(level2.get_diagnostic_record(input_handle));
}
```

The issue here is, that the driver or the driver manager decide to return SQL_SUCCESS_WITH_INFO the operation would fail. Since I discovered this issue purely by reading the code, I can not provide a specific combination of driver, driver manager and actions to produce an actual Bug. It still seemed worthy pointing out, though.

**Comment by MathMagique** [comment]
I added some rudimentary treatment for cases where `SQL_SUCCESS` defines the good path. Still need to encounter a database where this matters, though. ;-)

**Comment by pacman82** [comment]
I have been able to reproduce the behavior with an old (2010) ODBC Excel or Textdriver (csv) on Windows (32Bit). Setting the odbc version to 3.8 instead of 3 results in SQL_SUCCESS_WITH_INFO for a greater amount of drivers.
