### ISSUE TITLE
Release 3.4.0

### ISSUE THREAD

**Issue by alippai** [blue-yonder/turbodbc#259]
The CHANGELOG contains release 3.4.0, but it's not available on Pypi or Conda.
Are there any issues or PRs pending we can help test?

**Comment by fjetter** [comment]
The changelog was there but there was no actual release yet. I just changed this and once the build pipelines are through, it should be available

**Comment by alippai** [comment]
The pipelines failed I think.

**Comment by fjetter** [comment]
See #260
