### ISSUE TITLE
QUESTION: .whl files available for Windows 10 users?

### ISSUE THREAD

**Issue by pybokeh** [blue-yonder/turbodbc#277]
As the title states, are there any .whl files available for Windows 10 users that don't have access to build/compile tools?  I typically visit [here](https://www.lfd.uci.edu/~gohlke/pythonlibs/) and also searched at Anaconda's [repo](https://anaconda.org/conda-forge/turbodbc/files), but could not find any available .whl files.

**Comment by dhirschfeld** [comment]
`anaconda.org` is a repository for *`conda`* packages. Is there a particular reason you don't want to just use `conda`?

**Comment by pybokeh** [comment]
No particular reason, I just have a preference to use just venv and our users don't have admin rights to install Anaconda or build/compiler tools, but apparently can install vanilla Python.

**Comment by xhochy** [comment]
One of the main ideas of miniconda is that you don't need administration rights to install. You can unpack it at any location and run it from there.

Wheels won't happen as long as there is no volunteer to build them.

**Comment by pybokeh** [comment]
Thanks!  I was just wondering if there were existing wheels available that I was not aware of.  My intent was not to suggest or demand wheels be made.
