### ISSUE TITLE
Is kerberos supported?

### ISSUE THREAD

**Issue by alippai** [blue-yonder/turbodbc#281]
I don't see any mentions about it, but maybe it's only ODBC driver specific.

**Comment by pacman82** [comment]
Hi @alippai, the ODBC standard does not concern itself with kerberos. As far as authentication is concerned, ODBC allows for a username and a password if connecting via a Data Source Name (DSN). More database specific (i.e. driver specific options) can be specified in the configuration files, or be provided if connecting using an ODBC connection String. Both options do not concern this libary. It will pass any connection string on to the driver without complaint.

**Comment by alippai** [comment]
Thanks!
