### ISSUE TITLE
GIL in cursor.execute() if using prepared statement params

### ISSUE THREAD

**Issue by alippai** [blue-yonder/turbodbc#283]
I'm using a FastAPI webserver server (with uvicorn, single process), which handles non-async requests in separate threads (`loop.run_in_executor()`).

I create the turbodbc DB connections separately in each request. So if I have 6 different concurrent request 6 different connections will be used, one in each thread. This way I have 6x(1 request, 1 thread, 1 connection, 1 cursor, 1 execute() and no fetch). The problem is if I have a slow query in one of the endpoints, the `cursor.execute()` call locks up the 5 other requests too, the server becomes unresponsive until the result is returned. 

I see that this was an issue previously (https://github.com/blue-yonder/turbodbc/pull/222, https://github.com/blue-yonder/turbodbc/pull/80) but it supposed to be fixed now, shouldn't it?

**Comment by xhochy** [comment]
The GIL should be released here: https://github.com/blue-yonder/turbodbc/blob/80a29a7edfbdabf12410af01c0c0ae74bfc3aab4/cpp/turbodbc_python/Library/src/python_bindings/cursor.cpp#L12-L15

Could it be that some other function is holding the GIL? I know this is hard to debug/profile thus I'm unsure how to verify/reproduce this without having your exact setup.

**Comment by alippai** [comment]
I'll try to create a small example, but I'm 99,9% sure it's the cursor.execute() as all other requests take exactly that amount of time as the longest execute().

**Comment by alippai** [comment]
I can reproduce it only using prepared statements, if there are no extra params to `execute()` (but I simply build the query instead) the lock doesn't happen.

**Comment by xhochy** [comment]
Nice that actually is a part where the GIL isn't released and cannot fully be released. We should though be able to release once the params were converted to C++ objects.

**Comment by xhochy** [comment]
Still, having an example that triggers this would be big step forward to get this fixed.

**Comment by alippai** [comment]
Output:
```
Total without params: 2.05
Total with params: 4.03
```
Script:
```python
import asyncio
from time import time

from shared.db import db_connection


def slow_query_without_params():
    connection = db_connection()
    cursor = connection.cursor()
    cursor.execute("SELECT SLEEP(2)")


def slow_query_with_params():
    connection = db_connection("Vertica", "wqdbinsighthist")
    cursor = connection.cursor()
    cursor.execute("SELECT ?::int, SLEEP(2)", [1])


async def main():
    start = time()
    loop = asyncio.get_running_loop()
    task1 = loop.run_in_executor(None, slow_query_without_params)
    task2 = loop.run_in_executor(None, slow_query_without_params)
    await asyncio.gather(task1, task2)
    print(f"Total without params: {round(time() - start, 2)}")

    start = time()
    loop = asyncio.get_running_loop()
    task1 = loop.run_in_executor(None, slow_query_with_params)
    task2 = loop.run_in_executor(None, slow_query_with_params)
    await asyncio.gather(task1, task2)
    print(f"Total with params: {round(time() - start, 2)}")


asyncio.run(main())
```

**Comment by alippai** [comment]
@xhochy I have zero C++ or pybind11 experience, so likely I won't be able to provide a patch, but let me know I can help with the python part or testing.

**Comment by xhochy** [comment]
@alippai Maarten made a nice blog post about GIL detection / profiling: https://www.maartenbreddels.com/perf/jupyter/python/tracing/gil/2021/01/14/Tracing-the-Python-GIL.html

Maybe you could give this a try here? Once we know where the GIL is held, it should be much simpler to get rid of it.

**Comment by alippai** [comment]
This is supercool! I don't have a system where I can run this now, but I'll set it up on my PC - sadly it'll take me a month to get to this fun :/
