### ISSUE TITLE
Pyarrow 2.0.0

### ISSUE THREAD

**Issue by zacqed** [blue-yonder/turbodbc#285]
Should setup.py be updated to include support for 2.0.0

https://github.com/blue-yonder/turbodbc/blob/80a29a7edfbdabf12410af01c0c0ae74bfc3aab4/setup.py#L218

**Comment by alippai** [comment]
And python 3.9 marked as supported `'Programming Language :: Python :: 3.9'`

**Comment by ldacey** [comment]
pyarrow 3.0 was released today. I only tested it briefly but my kernel in Jupyterhub died when I queried for 10 rows of data. It worked with pyarrow 2.0 right before I upgraded.

table = cursor.fetchallarrow()

Then when I tried to do table.to_pandas() or table.schema my kernel died.

**Comment by bjoernmeier** [comment]
Hi, we released Turbodbc 4.1.2 which is tested with python 3.9 and with the major arrow versions. So the python flag and the versions limitations are changed and you can use a new arrow version now.
