### ISSUE TITLE
pyarrow 3.0 - fetcharrow causes kernel to die when using table.schema or table.to_pandas

### ISSUE THREAD

**Issue by ldacey** [blue-yonder/turbodbc#289]
Interestingly enough, table.num_rows prints out the correct number of rows, but when I try to do anything with the table my kernel will crash for no reason.

I tried:
```
table.to_pandas()
table.schema
ds.write_dataset(table)
```

I also tried fetching batches and iterating over them, but it crashed my kernel no matter what.

```
pyarrow 3.0.0
fsspec 0.8.4
adlfs v0.5.9
pandas 1.2.1
numpy 1.19.5
turbodbc 4.1.1
```

**Comment by bjoernmeier** [comment]
Hi,

as we currenlty working on a release where the limit of pyarrow<2.0.0 is removed I was looking into this issue.
So far I can not reproduce it with the current information.
I guessed that `ds` is `import pyarrow.dataset as ds`.
With this I can not reproduce it as the `ds.write_dataset` requires more arguments. As this is a pyarrow function I would assume that if this crashes it is an arrow issue.
But if you can share more details and maybe a reproducing example we can have a look.

**Comment by xhochy** [comment]
My guess is that the segmentation fault comes from the fact that `turbodbc` was compiled against a different `pyarrow` version as you are currently using.

**Comment by xhochy** [comment]
`pyarrow` is only ABI-compatible in patch releases.

**Comment by ldacey** [comment]
Hi yes - I was able to install turbodbc a bit after this with pyarrow 3.0 and everything is working. It is possible that my image had a cached version of pyarrow installed with pip instead of conda-forge or something silly.
