### ISSUE TITLE
No pushes to master

### ISSUE THREAD

**Issue by xhochy** [blue-yonder/turbodbc#290]
Hey @bjoern-meier-by , please don't push to master and instead make PRs. They will get quickly reviewed if they are so small but CI is broken here due to the `numpy=1.20` release. You will also need to fix / pin that.

**Comment by bjoern-meier-by** [comment]
Hi, as the master was reported as green the idea was to get a release  from it without any new changes, so my change was purely the release but sadly fails.
I am currently working on fixing the builds an moving away from travis to get it working again.

**Comment by xhochy** [comment]
`turbodbc` CI breaks at least every 2-3 months due to new upstream releases, green master is only a snapshot at that time ;)

Feel free to open a draft PR with failing things. For most of the errors, I have probably a good intuition now what has gone wrong, that could save you some time.
