### ISSUE TITLE
Asynchronous DB Query Example

### ISSUE THREAD

**Issue by mdashkezari** [blue-yonder/turbodbc#300]
Thanks for this fantastic work!

Can you please share an example code showing how to write async db calls?
How to `await` the `cur.execute(query).fetchall()`?

A short example would be great; thanks!

I'm using Turboodbc + FastAPI (uvicorn) + MS SQL Server

**Comment by alippai** [comment]
Hi @mdashkezari,

in my experience the best you can do is using sync FastAPI calls. Use the `def results()` example found [here](https://fastapi.tiangolo.com/async/#in-a-hurry).

If you are mixing async and sync, you can do it using [`loop.run_in_executor()`](https://docs.python.org/3/library/asyncio-eventloop.html#asyncio.loop.run_in_executor)

Turbodbc is nice and fast, however as like other libraries it has bugs too, related ones: https://github.com/blue-yonder/turbodbc/issues/283, https://github.com/blue-yonder/turbodbc/issues/193

**Comment by mdashkezari** [comment]
thanks for sharing your thoughts @alippai 

I have a simple path operation called `dbQuery`, which runs a generic sql statement and returns the results; looks like this: 

```python
@router.get("/", 
            response_description="Returns the query results in text format.", 
            response_model=CMAPResponse
            )
def query(sql: str, serverName: Optional[str]=None, compression: Optional[str]=None):
    """
    Executes a `sql` statement and returns the results in form of a dataframe converted to string.
    """
    data, msg, err = dbQuery(app.main.conns, sql, serverName)    
    return {"data": data.to_pydict(), "message": msg, "error": err}


``` 

How should I modify it to incorporate `loop.run_in_executor()`?
Should `loop` be initialized at the application level, or should it be created/removed within the path operation above?

**Comment by alippai** [comment]
This doesn't have to be changed. Check the FastAPI docs, it runs `query` in a thread pool executor automatically, so the example you posted won't block.

This is the best performance you can achieve easily 👍 

P.S. Accepting an untrusted sql command as a string parameter via HTTP API sounds like a horrible idea from security and architecture perspective.

**Comment by mdashkezari** [comment]
The app is a bit more involved than this pseudo example, obviously not any command can be run against the db.
thanks.
