### ISSUE TITLE
Add support and tests for pyarrow 6.0

### ISSUE THREAD

**Issue by ldacey** [blue-yonder/turbodbc#324]
The latest pyarrow version has been released. I will follow the approach I took in #318 to prepare turbodbc for the new version.

**Comment by ldacey** [comment]
@alippai @xhochy hm for some reason this failed due to arrow-cpp. I don't see any direct reference to arrow-cpp in this library, so perhaps it is a conda feedstock issue? 

```
name: turbodbc
channels:
  - conda-forge
dependencies:
  - python=3.9
  - pyarrow=6.0.1
  - turbodbc=4.3.0
```

Result:
```
Encountered problems while solving:
  - package turbodbc-4.3.0-py39h511d044_0 requires arrow-cpp >=3.0.0,<3.0.1.0a0, but none of the providers can be installed
```

**Comment by xhochy** [comment]
You will need to wait for the bot to reissue the PR at https://github.com/conda-forge/turbodbc-feedstock/pull/59, should be there in 3-4h and then we can merge builds for arrow-cpp=6

**Comment by ldacey** [comment]
Sure, thanks for the quick response!

**Comment by alippai** [comment]
@ldacey now https://github.com/conda-forge/turbodbc-feedstock/pull/61 is ready. When it's merged to master the deploy will start and the release will be available shortly.

**Comment by alippai** [comment]
@ldacey https://anaconda.org/conda-forge/turbodbc 4.3.0 is available. Thanks @xhochy for the quick releases!

**Comment by ldacey** [comment]
Nice, thanks a lot. I was able to install 4.3.0 with the latest pyarrow version.
