### ISSUE TITLE
How to use arrow support with pip?

### ISSUE THREAD

**Issue by jorgecarleitao** [blue-yonder/turbodbc#348]
On Ubuntu 20, I am unable to install `turbodbc` with arrow support.

What I tried:

```bash
python3 --version  # Python 3.8.10
python3 -m venv venv
source venv/bin/activate
pip install -U pip
pip install turbodbc[arrow] --no-cache-dir # Successfully installed numpy-1.22.2 pyarrow-7.0.0 turbodbc-4.5.3

python -c "import turbodbc_arrow_support" # ModuleNotFoundError: No module named 'turbodbc_arrow_support'
```

Trying to use a cursor with a pyarrow Table fails with

> turbodbc.exceptions.Error: This installation of turbodbc does not support Apache Arrow extensions. Please install the `pyarrow` package. If you have built turbodbc from source, you may also need to reinstall turbodbc to compile the extensions.

Any ideas on what am I missing here?

**Comment by david-engelmann** [comment]
@jorgecarleitao Check out [my comment](https://github.com/blue-yonder/turbodbc/issues/351#issue-1212672663) on my issue I recently closed. It's based on Docker with Ubuntu 20.04, hope it helps!

**Comment by ldacey** [comment]
Confirming that this solution worked for me as well.

**Comment by xhochy** [comment]
With release 4.5.9, this should also be much better. Closing for now.
