### ISSUE TITLE
Failed to Build Turbodbc in Docker with Ubuntu 20.04 + Python 3.8 with Pip

### ISSUE THREAD

**Issue by david-engelmann** [blue-yonder/turbodbc#351]
I've been trying to build Turbodbc in a Docker container for weeks at this point and can not avoid the same error message. Up until a few weeks ago, the build would work. I'm totally at a loss at this point. I've tried building make, gcc, boost, arrow, and pybind11 from source. I've tried adding a slew of other dependencies. I've set DIRs and PATHs. I've tried pretty much every pip flag there is, from --no-cache-dir, --prefer-binary, --no-binary, --no-cache, --ignore-installed, --upgrade. If anyone has any suggestions, or approaches that allow for turbodbc to be installed in a docker container without conda, it would be very appreciated. 

Short Version of the Error:
```
 /usr/bin/ld: cannot find -lturbodbc.cpython-38-x86_64-linux-gnu
collect2: error: ld returned 1 exit status
error: command '/usr/bin/x86_64-linux-gnu-g++' failed with exit code 1
```
The General Docker setup is as follows:
OS Dependencies
```
RUN apt-get update && apt-get -y upgrade \
    && export DEBIAN_FRONTEND=noninteractive \
    && apt-get -y install --no-install-recommends \
       ca-certificates \
       build-essential \
       file \
       g++ \
       gcc \
       gdb \
       lsb-release \
       libboost-all-dev \
       libffi-dev \
       libpq-dev \
       libpython${PY_VERSION}-dev \
       libssl-dev \
       make \
       python3 \
       python3-pip \
       python3-wheel \
       python${PY_VERSION}-dev \
       python${PY_VERSION}-venv \
       software-properties-common \
       unixodbc \
       unixodbc-dev \ 
    && wget https://apache.jfrog.io/artifactory/arrow/$(lsb_release --id --short | tr 'A-Z' 'a-z')/apache-arrow-apt-source-latest-$(lsb_release --codename --short).deb \
    && apt-get install -y -V ./apache-arrow-apt-source-latest-$(lsb_release --codename --short).deb \
    && curl https://packages.microsoft.com/keys/microsoft.asc | apt-key add - \
    && curl https://packages.microsoft.com/config/ubuntu/${UBUNTU_VERSION}/prod.list > /etc/apt/sources.list.d/mssql-release.list \
    && apt-get update && apt-get -y upgrade \
    && wget -qO- --no-check-certificate https://packages.microsoft.com/keys/microsoft.asc | apt-key add - \
    && add-apt-repository "$(wget -qO- https://packages.microsoft.com/config/ubuntu/$UBUNTU_VERSION/mssql-server-2019.list)" \
    && apt-get update && apt-get -y upgrade \
    && apt-get -y install --no-install-recommends mssql-server \
    && ACCEPT_EULA=Y apt-get install --no-install-recommends -y msodbcsql17 \
    && ACCEPT_EULA=Y apt-get install --no-install-recommends -y mssql-tools \
    && apt-get update && apt-get -y upgrade 
```
Python Dependencies
```
# Virtual Enviroment - I've Tried with and without a venv
ENV VIRTUAL_ENV="/opt/venv"
RUN python3 -m venv ${VIRTUAL_ENV}
ENV PATH="$VIRTUAL_ENV/bin:$PATH"
RUN . $VIRTUAL_ENV/bin/activate

# WORKDIR /workspaces/project_name
# Get requirements.txt file
COPY ./requirements.txt .
COPY ./prerequirements.txt .

RUN . $VIRTUAL_ENV/bin/activate && pip3 install --upgrade pip setuptools wheel \
  && pip3 install --no-cache-dir wheel pybind11 numpy pyarrow==5.0.0 setuptools cmake six \
  && pip3 install --no-cache-dir -r prerequirements.txt \
  && python3 -c "import pyarrow; pyarrow.create_library_symlinks()" \
  && pip3 install --no-cache-dir -r requirements.txt
```
Contents of requirements files
```
# pre
pybind11==2.8.1
numpy==1.21.2
pandas==1.3.3
six==1.16.0
pyarrow==5.0.0

# regular
SQLAlchemy==1.4.35
pyodbc==4.0.32
mysql-connector-python==8.0.26
turbodbc==4.5.3
```
This is the results of "pip list" from the container after turbodbc fails to install
```
cmake                  3.22.4
greenlet               1.1.2
mysql-connector-python 8.0.26
numpy                  1.21.2
pandas                 1.3.3
pip                    22.0.4
pkg_resources          0.0.0
protobuf               3.20.1
pyarrow                5.0.0
pybind11               2.8.1
pyodbc                 4.0.32
python-dateutil        2.8.2
pytz                   2022.1
setuptools             62.1.0
six                    1.16.0
SQLAlchemy             1.4.35
wheel                  0.37.1
```
I'll also attach the pip logs for the failed turbodbc installation attempt. [turbo_error.log](https://github.com/blue-yonder/turbodbc/files/8543273/turbo_error.log)

Thank you for all of your help!

**Comment by SamHummerstone** [comment]
I am having the exact same issue with python version 3.10 and turbodbc version 4.5.3. Would love to know how to resolve this error.

**Comment by david-engelmann** [comment]
@SamHummerstone I've tried to build with various versions of python and various versions of turbodbc and receive the same error. If I'm able to resolve it, I will let you know!

**Comment by david-engelmann** [comment]
I've come up with my minimal viable dockerfile for installing Turbodbc without conda. The following dockerfile will be based on Ubuntu 20.04 (focal). It was tested with Ubuntu 18.04 (bionic) and was successful as well.

```
FROM mcr.microsoft.com/vscode/devcontainers/base:0-focal

RUN apt-get update && export DEBIAN_FRONTEND=noninteractive \
     && apt-get -y install --no-install-recommends \
        build-essential \ 
        default-libmysqlclient-dev \
        libpython3-dev \
        libboost-all-dev \
        python3 \
        python3-pip \
        python3-wheel \
        python3-dev \
        python3-venv \
        software-properties-common \
        unixodbc \
        unixodbc-dev \
    && curl https://packages.microsoft.com/keys/microsoft.asc | apt-key add - \
    && curl https://packages.microsoft.com/config/ubuntu/20.04/prod.list > /etc/apt/sources.list.d/mssql-release.list \
    && apt-get update && apt-get -y upgrade \
    && wget -qO- --no-check-certificate https://packages.microsoft.com/keys/microsoft.asc | apt-key add - \
    && add-apt-repository "$(wget -qO- https://packages.microsoft.com/config/ubuntu/20.04/mssql-server-2019.list)" \
    && apt-get update && apt-get -y upgrade \
    && apt-get -y install --no-install-recommends mssql-server \
    && ACCEPT_EULA=Y apt-get install --no-install-recommends -y msodbcsql17 \
    && ACCEPT_EULA=Y apt-get install --no-install-recommends -y mssql-tools \
    && apt-get update && apt-get -y upgrade

# Change to Project Base Folder
WORKDIR /workspaces/project_name

ARG VIRTUAL_ENV="/opt/venv"
ENV VIRTUAL_ENV $VIRTUAL_ENV
RUN python3 -m venv ${VIRTUAL_ENV}
ENV PATH="$VIRTUAL_ENV/bin:$PATH"
RUN . ${VIRTUAL_ENV}/bin/activate

# Get requirements.txt file
COPY requirements.txt .

# Install Dependencies
RUN pip3 install -U pip==22.0.4 setuptools==45.2.0 wheel==0.37.1 \
    && pip3 install --no-cache-dir -r requirements.txt \
    && python3 -c "import pyarrow; pyarrow.create_library_symlinks()" \
    && CFLAGS="-D_GLIBCXX_USE_CXX11_ABI=0" pip3 install --no-cache-dir turbodbc

# Clean up
RUN apt-get autoremove -y \
    && apt-get clean -y \
    && rm -rf /var/lib/apt/lists/*
```

The requirements.txt is extremely small but to build with numpy and arrow support both packages need to be pip installed before turbodbc can be pip installed.

```
numpy>=1.21.2
pyarrow>=7.0.0
```

Here is the output of pip list from the container

```
Package       Version

------------- -------

numpy         1.22.3

pip           22.0.4

pkg_resources 0.0.0

pyarrow       8.0.0

setuptools    45.2.0

turbodbc      4.5.3

wheel         0.37.1
```
Confirming turbodbc is present and numpy and arrow is supported

![image](https://user-images.githubusercontent.com/81196676/167730395-a7f1c8e2-6e28-46c8-b75d-f9bbd64587d6.png)

**Comment by david-engelmann** [comment]
> I am having the exact same issue with python version 3.10 and turbodbc version 4.5.3. Would love to know how to resolve this error.

[Check out this setup, hope it helps!](https://github.com/blue-yonder/turbodbc/issues/351#issuecomment-1122946938)

**Comment by SamHummerstone** [comment]
Hi David,

Glad to see you've got it working, do you know exactly what change you made to fix this? And any ideas why this seemed to happen randomly to a few people?

**Comment by david-engelmann** [comment]
> Hi @david-engelmann
> 
> Glad to see you've got it working, do you know exactly what change you made to fix this? And any ideas why this seemed to happen randomly to a few people?

I had a few observations. Upgrading pip, setuptools and wheel before installing the prerequisites numpy and/or arrow seemed to help. For Arrow creating the library symlinks was important. As far as the specific error message ever one was getting, `cannot find -lturbodbc.cpython-`, the addition of CFLAGS="-D_GLIBCXX_USE_CXX11_ABI=0" seemed to allow the building of wheels. The OS dependencies part can definitely change depending on the setup of the database. Hopefully, I've saved you so heartache and time.

**Comment by peter-wimsey** [comment]
>     && python3 -c "import pyarrow; pyarrow.create_library_symlinks()" \
>     && CFLAGS="-D_GLIBCXX_USE_CXX11_ABI=0" pip3 install --no-cache-dir turbodbc

@david-engelmann Thank you very much. That does indeed seem to work. How did you figure out this trickery?

**Comment by david-engelmann** [comment]
> > ```
> > && python3 -c "import pyarrow; pyarrow.create_library_symlinks()" \
> > && CFLAGS="-D_GLIBCXX_USE_CXX11_ABI=0" pip3 install --no-cache-dir turbodbc
> > ```
> 
> @david-engelmann Thank you very much. That does indeed seem to work. How did you figure out this trickery?

@peter-wimsey I've been using Turbodbc for the past two+ years. I absolutely love its performance but I've had to do lots of troubleshooting when installing locally on my machines and the machines of others I work with. I made the jump to Docker to help that installation process and just slogged through getting it to compile. It helped to have a working local setup and then I stripped it down to the minimum viable docker setup for the people!

**Comment by blake-hamm** [comment]
Just wanted to comment in case anyone is using poetry. I was able to get this to work in the poetry environment (replacing the latter half of @david-engelmann's solution):
```
# Install poetry package requirements
COPY poetry.lock pyproject.toml ./
RUN poetry install

# Hacky install turbodbc
RUN poetry run python -c "import pyarrow; pyarrow.create_library_symlinks()"
RUN CFLAGS="-D_GLIBCXX_USE_CXX11_ABI=0" poetry run pip install --no-cache-dir turbodbc
```
