### ISSUE TITLE
Can't install Turboodbc in docker enviroment

### ISSUE THREAD

**Issue by leandro529** [blue-yonder/turbodbc#352]
Hello I have tried to deploy an image in docker that contains the turboodbc library.
Running pip install turboodbc gives me this error.

n-38-x86_64-linux-gnu.so -Wl,-rpath,$ORIGIN
#50 327.9   /usr/bin/ld: cannot find -lturbodbc.cpython-38-x86_64-linux-gnu
#50 327.9   collect2: error: ld returned 1 exit status
#50 327.9   error: command '/usr/bin/g++' failed with exit code 1
#50 328.0   error: subprocess-exited-with-error
#50 328.0
#50 328.0   × Running setup.py install for turbodbc did not run successfully.
#50 328.0   │ exit code: 1
#50 328.0   ╰─> See above for output.
#50 328.0
#50 328.0   note: This error originates from a subprocess, and is likely not a problem with pip.
#50 328.0   full command: /usr/local/bin/python -u -c '
#50 328.0   exec(compile('"'"''"'"''"'"'
#50 328.0   # This is <pip-setuptools-caller> -- a caller that pip uses to run setup.py
#50 328.0   #
#50 328.0   # - It imports setuptools before invoking setup.py, to enable projects that directly
#50 328.0   #   import from `distutils.core` to work with newer packaging standards.
#50 328.0   # - It provides a clear error message when setuptools is not installed.
#50 328.0   # - It sets `sys.argv[0]` to the underlying `setup.py`, when invoking `setup.py` so
#50 328.0   #   setuptools doesn'"'"'t think the script is `-c`. This avoids the following warning:
#50 328.0   #     manifest_maker: standard file '"'"'-c'"'"' not found".
#50 328.0   # - It generates a shim setup.py, for handling setup.cfg-only projects.
#50 328.0   import os, sys, tokenize
#50 328.0
#50 328.0   try:
#50 328.0       import setuptools
#50 328.0   except ImportError as error:
#50 328.0       print(
#50 328.0           "ERROR: Can not execute `setup.py` since setuptools is not available in "
#50 328.0           "the build environment.",
#50 328.0           file=sys.stderr,
#50 328.0       )
#50 328.0       sys.exit(1)
#50 328.0
#50 328.0   __file__ = %r
#50 328.0   sys.argv[0] = __file__
#50 328.0
#50 328.0   if os.path.exists(__file__):
#50 328.0       filename = __file__
#50 328.0       with tokenize.open(__file__) as f:
#50 328.0           setup_py_code = f.read()
#50 328.0   else:
#50 328.0       filename = "<auto-generated setuptools caller>"
#50 328.0       setup_py_code = "from setuptools import setup; setup()"
#50 328.0
#50 328.0   exec(compile(setup_py_code, filename, "exec"))
#50 328.0   '"'"''"'"''"'"' % ('"'"'/tmp/pip-install-bx7n_618/turbodbc_23852eb7d4d349609e69b687d99f7495/setup.py'"'"',), "<pip-setuptools-caller>", "exec"))' install --record /tmp/pip-record-wa41bumo/install-record.txt --single-version-externally-managed --user --prefix= --compile --install-headers /home/airflow/.local/include/python3.8/turbodbc
#50 328.0   cwd: /tmp/pip-install-bx7n_618/turbodbc_23852eb7d4d349609e69b687d99f7495/
#50 328.0   Running setup.py install for turbodbc: finished with status 'error'
#50 328.0 error: legacy-install-failure
#50 328.0
#50 328.0 × Encountered error while trying to install package.
#50 328.0 ╰─> turbodbc
#50 328.0
#50 328.0 note: This is an issue with the package mentioned above, not pip.
#50 328.0 hint: See above for output from the failure.

**Comment by david-engelmann** [comment]
I've recently submitted a similar issue - https://github.com/blue-yonder/turbodbc/issues/351. I'm still unable to build in docker without conda. ` /usr/bin/ld: cannot find -lturbodbc.cpython-38-x86_64-linux-gnu` is the same short form error message as I receive. Steps to reproduce can be found in the issue.

**Comment by david-engelmann** [comment]
I've closed out my issue and added a [minimum viable dockerfile setup here](https://github.com/blue-yonder/turbodbc/issues/351#issuecomment-1122946938). Hope this helps!

**Comment by leandro529** [comment]
@david-engelmann   Thank you. I've Added the flag CFLAGS="-D_GLIBCXX_USE_CXX11_ABI=0 and my image compiles.
 I share a link in case someone wants to delve into the error. https://gcc.gnu.org/onlinedocs/libstdc++/manual/using_dual_abi.html

**Comment by david-engelmann** [comment]
> @david-engelmann Thank you. I've Added the flag CFLAGS="-D_GLIBCXX_USE_CXX11_ABI=0 and my image compiles. I share a link in case someone wants to delve into the error. https://gcc.gnu.org/onlinedocs/libstdc++/manual/using_dual_abi.html

Love to Hear It! Happy Hackings!
