### ISSUE TITLE
Make execute() return the cursor

### ISSUE THREAD

**Issue by keitherskine** [blue-yonder/turbodbc#37]
It would be handy if the cursor's `execute()` function returned the cursor itself (rather than `None`) so that it would be possible to write code like this:
```python
rows = cursor.execute('select * from my_table').fetchall()
```
rather than having to take two bites at it:
```python
cursor.execute('select * from my_table')
rows = cursor.fetchall()
```
Ditto for `executemany()`.

**Comment by MathMagique** [comment]
Hey Keith! Thanks for the suggestion. [PEP 249](https://www.python.org/dev/peps/pep-0249/) does not specify the return value of `execute()`, but your suggestion makes total sense and also does not violate the standard.
