### ISSUE TITLE
Allocating more than one Environment within a process is undefined behaviour

### ISSUE THREAD

**Issue by pacman82** [blue-yonder/turbodbc#44]
While wrapping ODBC for rust I noted race conditions while executing tests in parallel. Turns out it is undefined behaviour to have more than one environment allocated within a process.

```c++
#include "turbodbc/connect.h"
#include <cpp_odbc/make_environment.h>

turbodbc::connection turbodbc::connect(std::string const & connection_string)
{
	auto environment = cpp_odbc::make_environment();
	return {environment->make_connection(connection_string)};
}
```

The above code implies that turbodbc allocates an environment together with a connection, this makes having more than one connection at a time illegal within turbodbc. Due to pythons global interpreter lock I would have a hard time reproducing the same race condition I stumbled upon in unsafe rust, yet I wanted to race awareness of the issue in case there might be other issues.

See https://github.com/Koka/odbc-rs/issues/12 for the original issue.

**Comment by MathMagique** [comment]
Thanks for the hint! I have not seen any practical issues with this one so far, but I could add a test that uses multiple connections. If fixing is required, an easy fix would be to store a global `weak_ptr` to the `cpp_odbc::environment` object and use this to create new environments as needed.

**Comment by pacman82** [comment]
As the link to the discussion in odbc-rs indicates I actually did not find this issue by reading the ODBC reference. Only secondary source seem to claim this a problem. For practical purposes you are probably fine due to the global interpreter lock of python.

**Comment by MathMagique** [comment]
I have added a test scenario in which I use multiple connections. No problems. I will close this for now.
