### ISSUE TITLE
tuple should be valid parameter type for parameters

### ISSUE THREAD

**Issue by bjoernmeier** [blue-yonder/turbodbc#5]
Using tuples as parameters for an INSERT statement results in the following Exception.

ArgumentError                             Traceback (most recent call last)
<ipython-input-4-08e185147d3f> in <module>()
----> 1 c.execute("INSERT INTO {0} VALUES (?, ?, ?, ?) RETURNING {0}.id".format('users'), (7, 'Max', 'Mustermann', None))

/home/vagrant/.virtualenvs/turbodbc_sqlalchemy/local/lib/python2.7/site-packages/turbodbc/exceptions.pyc in wrapper(*args, **kwds)
     23     def wrapper(*args, **kwds):
     24         try:
---> 25             return f(*args, **kwds)
     26         except InternError as e:
     27             raise DatabaseError(str(e))

/home/vagrant/.virtualenvs/turbodbc_sqlalchemy/local/lib/python2.7/site-packages/turbodbc/cursor.py in execute(self, sql, parameters)
     40         self.impl.prepare(sql)
     41         if parameters:
---> 42             self.impl.add_parameter_set(parameters)
     43         self.impl.execute()
     44         self.rowcount = self.impl.get_row_count()

ArgumentError: Python argument types in
    Cursor.add_parameter_set(Cursor, tuple)
did not match C++ signature:
    add_parameter_set(turbodbc::cursor {lvalue}, std::vector<boost::optional<boost::variant<long, std::string, bool, double, boost::gregorian::date, boost::posix_time::ptime, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_> >, std::allocator<boost::optional<boost::variant<long, std::string, bool, double, boost::gregorian::date, boost::posix_time::ptime, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_> > > >)

**Comment by MathMagique** [comment]
Fixed
