### ISSUE TITLE
Cannot connect

### ISSUE THREAD

**Issue by yalwan-scee** [blue-yonder/turbodbc#51]
I'm pretty sure I have a valid ODBC setup

If I do `pyodbc.connect('DSN=dsn')` it works fine

With turboodbc, I get this:

```Traceback (most recent call last):
  File "/home/yalwan/venv/lib/python3.5/site-packages/turbodbc/exceptions.py", line 31, in wrapper
    return f(*args, **kwds)
  File "/home/yalwan/venv/lib/python3.5/site-packages/turbodbc/connect.py", line 40, in connect
    connection = Connection(intern_connect(_make_connection_string(dsn, **kwargs)))
turbodbc_intern.Error: ODBC error
state: IM002
native error code: 0
message: [unixODBC][Driver Manager]Data source name not found, and no default driver specified

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/yalwan/venv/lib/python3.5/site-packages/turbodbc/exceptions.py", line 33, in wrapper
    raise DatabaseError(str(e))
turbodbc.exceptions.DatabaseError: ODBC error
state: IM002
native error code: 0
message: [unixODBC][Driver Manager]Data source name not found, and no default driver specified
```

And not only this, but it happens regardless of what I pass to connect, empty string, DSN, or DSN-less with the parameters specified inline.

```pip list --format columns
Package    Version 
---------- --------
appdirs    1.4.2   
packaging  16.8    
pip        9.0.1   
pybind11   2.0.1   
pyodbc     4.0.13  
pyparsing  2.1.10  
setuptools 34.3.1  
six        1.10.0  
turbodbc   1.0.3   
wheel      0.30.0a0
```

The database type I am trying to connect to is netezza (IBM puredata for analytics).

Please let me know if you require more information.

**Comment by MathMagique** [comment]
The `turbodbc.connect()` statement would be nice ;-).

If you type `turbodbc.connect("dsn=DSN")`, turbodbc will try to establish a connection with a database called "dsn=DSN" instead of setting the data source name.

Any of this should work:
```
turbodbc.connect("dsn")
turbodbc.connect(dsn="dsn")
turbodbc.connect(dsn="dsn", some_other_option="will be passed to connection string")
```

**Comment by yalwan-scee** [comment]
Ah, my bad I understand whats going on here.
Is there some documentation for this module? Sorry about wasting your time.

**Comment by MathMagique** [comment]
You did not waste my time, you indicated that the documentation may need some improvement, and I am grateful for that.

There is no exhaustive documentation _yet_, but the [README](https://github.com/blue-yonder/turbodbc/blob/master/README.md) contains some documentation. You need to scroll down to "basic usage".

Anyway, glad you are able to connect! Please let me know if you encounter any issues and how performance turns out for IBM puredata (never heard of that one before).

**Comment by yalwan-scee** [comment]
Is there another channel I might contact you by, if I may?

**Comment by MathMagique** [comment]
Just drop me an e-mail (see [setup.py](https://github.com/blue-yonder/turbodbc/blob/master/setup.py#L140)) or tweet me at twitter ([@turbodbc](https://twitter.com/turbodbc)), as you find appropriate.
