### ISSUE TITLE
Request for fetchmanynumpy

### ISSUE THREAD

**Issue by yalwan-scee** [blue-yonder/turbodbc#53]
Fetchall numpy is a good option when the data set fits in memory, but what about when we need to operate in batches? Can we get support for fetchmany numpy?

**Comment by MathMagique** [comment]
That makes perfect sense. There are a few differences to consider with respect to `fetchmany()`.
* Retrieving an iterator that does just that seems more Pythonic
* `fetchmany()` features dedicated a dedicated `size` parameter that defaults to the `arraysize` attribute. Implementation becomes much simpler without these parameters. Turbodbc already exposes its buffer sizes when creating connections, and these buffer sizes should be used for batched numpy support.

**Comment by yalwan-scee** [comment]
I wanted to try my hand at writing this one myself.

Should the approach be to modify?
pybind11::object numpy_result_set::fetch_all

I see we have calls to fetch_next_batch()

Should we refactor this method to a fetch_batch and fetch_all is just a loop above the new fetch_batch, and then do something similar with the python convenience methods where one produces the full result set and another produces an iterator over the result set?

**Comment by MathMagique** [comment]
That sounds great!

In my head I would modify the C++ `numpy_result_set::fetch_all()` to return a dictionary for the next batch only. I'd probably rename it to `numpy_result_set::fetch_next_batch()` as well.

For the existing functionality, this would mean that Python's `fetchallnumpy()` needs some additional logic to concatenate all batches while preserving the masks of the batches. This is currently done in C++, but seems needless in retrospect.

For the new functionality, I would implement an iterator (in Python) that uses the `numpy_result_set::fetch_next_batch()` functionality.

That's just from the back of my head, and I may have missed some details or roadblocks there.

**Comment by yalwan-scee** [comment]
I'd be a little careful, naive concatenation could needlessly harm performance for the fetchallnumpy

**Comment by MathMagique** [comment]
The current way is not sophisticated and not as ideal as possible, since it resizes arrays after each batch anyways. So no harm done.

https://github.com/blue-yonder/turbodbc/blob/master/cpp/turbodbc_numpy/Library/src/binary_column.cpp#L67

**Comment by yaxxie** [comment]
What are we resizing there? It doesn't look like a numpy array, or am I mistaken?

**Comment by MathMagique** [comment]
Actually, it is, see [this reference](https://docs.scipy.org/doc/numpy/reference/c-api.array.html#c.PyArray_Resize)

**Comment by yaxxie** [comment]
9840685 closes  this.

**Comment by MathMagique** [comment]
done in PR #69
