### ISSUE TITLE
Feature-Request: Release GIL

### ISSUE THREAD

**Issue by chmp** [blue-yonder/turbodbc#77]
As a (generic) user, I want turbodbc to release the GIL to allow concurrent usage.

Currently, turbodbc does not release the GIL. Thereby, it is not possible to use python threading effectively with turbodbc. By releasing the GIL, turbodbc would allow running multiple queries concurrently or execute queries in the background of an jupyter notebook without locking it completely. For example, [psycopg](http://initd.org/psycopg/docs/) does release the GIL.

**Comment by chmp** [comment]
I'll give it a try and report back how it goes :). Small caveat: I'm mostly interested in the `fetchallnumpy` code path and won't look much at other place (performance and all).

**Comment by MathMagique** [comment]
Fixed in #80

**Comment by yaxxie** [comment]
Just FYI, just came across this, and am actually happy because i'm about to test using this in threaded fashion in my project. If this works as I expect I can double throughput of my application, so I'd like to add my thanks for this contribution.
