### ISSUE TITLE
growth strategy for unknown parameter types does not work with EXASOL

### ISSUE THREAD

**Issue by bjoernmeier** [blue-yonder/turbodbc#8]
If you execute a parametrised query where EXASOL does not know exactly the type, like:
`cursor.execute("SELECT x from (values(1), (2)) as tbl (x) where x = ?;" , [2,])`
turbodbc allocates a huge amount of memory. This combined with the default value for parameter_sets_to_buffer could lead to a MemoryError.

**Comment by MathMagique** [comment]
Fixed
