### ISSUE TITLE
Transactions not supported by Hortonworks ODBC driver for Hive

### ISSUE THREAD

**Issue by jesaerys** [blue-yonder/turbodbc#87]
I get the following error when I try to connect to Hive:

```
DatabaseError: ODBC error
state: HYC00
native error code: 11470
message: [Hortonworks][ODBC] (11470) Transactions are not supported.
```

I can successfully connect with this same driver and DSN in `isql`.

My understanding is that this happens because turbodbc enforces explicit transactions with `Connection.commit`. Are there plans to add an autocommit option for `turbodbc.connect`? Perhaps that would alleviate errors like this.

Thanks!

**Comment by keitherskine** [comment]
Just FYI, autocommit has been requested in #41 .

**Comment by MathMagique** [comment]
Hi! Thanks for reporting. Seeing that more users have an issue with the default, I mentally bumped up the priority of the autocommit feature.

**Comment by MathMagique** [comment]
I have added an `autocommit` option that you can provide before connecting to your database. That should help with connecting to Hive. The feature is part of turbodbc 1.1.2 which will be released in the next minutes by the CI builds I have triggered. Usage:

```
from turbodbc import connect, make_options

options = make_options(autocommit=True)
connection = connect(dsn="My Hive data source", turbodbc_options=options)
```

See here for more extensive [documentation](http://turbodbc.readthedocs.io/en/latest/pages/advanced_usage.html#autocommit)
