### ISSUE TITLE
Feedback: works with Teradata

### ISSUE THREAD

**Issue by jesaerys** [blue-yonder/turbodbc#88]
This isn't an issue. I just wanted to let y'all know that I've successfully connected to Teradata using turbodbc. No special options or configuration required on my part.

Thanks for making this amazing package!

**Comment by MathMagique** [comment]
Thank you! I am very pleased to hear that :-). Have you checked that strings containing unicode characters are handled correctly? Do you have some rough estimate how performance compares to pyodbc or whatever other ODBC module you have tested?

If you find the time and motiviation, it would be great to have a page for Teradata (similar to the [Exasol page](http://turbodbc.readthedocs.io/en/latest/pages/databases/exasol.html), for example) in the databases section of the turbodbc documentation.

Anyway, thanks for the feedback!

**Comment by jesaerys** [comment]
I haven't tested unicode strings, but I should be able to look into that when I get a chance.

The only other ODBC module I've used is pyodbc. I haven't done any actual benchmarks with the Teradata driver, but my experience so far is that `fetchall` performs about the same between turbodbc and pyodbc, while doing INSERTs with `executemany` is *significantly* faster in turbodbc. This is no surprise since pyodbc executes each INSERT individually (see https://github.com/mkleehammer/pyodbc/issues/120).

I'll also take a look at the docs when I have time.

**Comment by zach-morris** [comment]
I'm looking for documentation on getting turbodbc to work with Teradata, and there doesn't seem to be any documentation on it anywhere (other than this issue saying it works).  Any additional info on how?

**Comment by pacman82** [comment]
Not having access to a terradata DB nor time to test it, but with any database you need three puzzle pieces to make them work with turbodbc:

1. ODBC driver manager: Given on windows, for other OS use <http://www.unixodbc.org/>
2. ODBC driver: Of course the ODBC driver must be compiled for your platform. Here is the link to the terradata windows driver: <https://downloads.teradata.com/download/connectivity/odbc-driver/windows>
3. ODBC connection string (will be passed to turbodbc as an argument): <https://www.connectionstrings.com/teradata-odbc-driver/>

Putting all of these together it should work.
