### ISSUE TITLE
Provide __version__ package variable

### ISSUE THREAD

**Issue by FlorianWilhelm** [blue-yonder/turbodbc#96]
Hi there! Almost all Python libraries I know have a package variable `__version__` that provides the current version as a string. This is nice if you want check in an interactive session with what version you are dealing and in general for debugging purposes. I know that another great Blue Yonder package called PyScaffold provides this out of the box ;-)

**Comment by MathMagique** [comment]
I heard that PyScaffold also introduces unwanted dependencies ;-). Valid point about the `__version__` variable, though.

**Comment by FlorianWilhelm** [comment]
That really is a misconception, only during development, not when you ship your package.
